<?php

namespace Database\Seeders;

use App\Models\SystemString;
use Illuminate\Database\Seeder;

class SystemStringSeeder extends Seeder
{
    public function run(): void
    {
        $strings = [
            // ─── Auth ─────────────────────────────────────────────────────────
            ['key' => 'auth.login', 'group' => 'auth', 'az' => 'Daxil ol', 'ru' => 'Войти', 'en' => 'Login'],
            ['key' => 'auth.logout', 'group' => 'auth', 'az' => 'Çıxış', 'ru' => 'Выйти', 'en' => 'Logout'],
            ['key' => 'auth.register', 'group' => 'auth', 'az' => 'Qeydiyyat', 'ru' => 'Регистрация', 'en' => 'Register'],
            ['key' => 'auth.login_success', 'group' => 'auth', 'az' => 'Uğurla daxil oldunuz', 'ru' => 'Вход выполнен успешно', 'en' => 'Logged in successfully'],
            ['key' => 'auth.login_failed', 'group' => 'auth', 'az' => 'Giriş məlumatları yanlışdır', 'ru' => 'Неверные данные для входа', 'en' => 'Invalid credentials'],
            ['key' => 'auth.register_success', 'group' => 'auth', 'az' => 'Uğurla qeydiyyatdan keçdiniz', 'ru' => 'Регистрация прошла успешно', 'en' => 'Registered successfully'],
            ['key' => 'auth.register_failed', 'group' => 'auth', 'az' => 'Qeydiyyat uğursuz oldu', 'ru' => 'Регистрация не удалась', 'en' => 'Registration failed'],
            ['key' => 'auth.logout_success', 'group' => 'auth', 'az' => 'Uğurla çıxış etdiniz', 'ru' => 'Вы вышли из системы', 'en' => 'Logged out successfully'],
            ['key' => 'auth.forgot_password', 'group' => 'auth', 'az' => 'Şifrəni unutdum', 'ru' => 'Забыли пароль', 'en' => 'Forgot password'],
            ['key' => 'auth.reset_password', 'group' => 'auth', 'az' => 'Şifrəni yenilə', 'ru' => 'Сбросить пароль', 'en' => 'Reset password'],
            ['key' => 'auth.email', 'group' => 'auth', 'az' => 'Email', 'ru' => 'Электронная почта', 'en' => 'Email'],
            ['key' => 'auth.username', 'group' => 'auth', 'az' => 'İstifadəçi adı', 'ru' => 'Имя пользователя', 'en' => 'Username'],
            ['key' => 'auth.password', 'group' => 'auth', 'az' => 'Şifrə', 'ru' => 'Пароль', 'en' => 'Password'],
            ['key' => 'auth.remember_me', 'group' => 'auth', 'az' => 'Məni xatırla', 'ru' => 'Запомни меня', 'en' => 'Remember me'],
            ['key' => 'auth.no_account', 'group' => 'auth', 'az' => 'Hesabınız yoxdur?', 'ru' => 'Нет аккаунта?', 'en' => 'No account?'],
            ['key' => 'auth.have_account', 'group' => 'auth', 'az' => 'Hesabınız var?', 'ru' => 'Уже есть аккаунт?', 'en' => 'Already have an account?'],
            ['key' => 'auth.forgot_password_desc', 'group' => 'auth', 'az' => 'Email ünvanınızı daxil edin, şifrə sıfırlama linki göndərəcəyik', 'ru' => 'Введите email, мы отправим ссылку для сброса пароля', 'en' => 'Enter your email and we will send a password reset link'],
            ['key' => 'auth.reset_link_sent', 'group' => 'auth', 'az' => 'Sıfırlama linki göndərildi', 'ru' => 'Ссылка для сброса отправлена', 'en' => 'Reset link sent'],
            ['key' => 'auth.reset_link_sent_desc', 'group' => 'auth', 'az' => 'Email ünvanınızı yoxlayın', 'ru' => 'Проверьте вашу почту', 'en' => 'Check your inbox'],
            ['key' => 'auth.send_reset_link', 'group' => 'auth', 'az' => 'Sıfırlama linki göndər', 'ru' => 'Отправить ссылку', 'en' => 'Send reset link'],
            ['key' => 'auth.new_password', 'group' => 'auth', 'az' => 'Yeni şifrə', 'ru' => 'Новый пароль', 'en' => 'New password'],
            ['key' => 'auth.confirm_password', 'group' => 'auth', 'az' => 'Şifrəni təsdiqlə', 'ru' => 'Подтвердите пароль', 'en' => 'Confirm password'],
            ['key' => 'auth.password_reset_success', 'group' => 'auth', 'az' => 'Şifrə uğurla yeniləndi', 'ru' => 'Пароль успешно сброшен', 'en' => 'Password reset successfully'],
            ['key' => 'auth.verifying_email', 'group' => 'auth', 'az' => 'Email doğrulanır...', 'ru' => 'Проверка email...', 'en' => 'Verifying your email address...'],
            ['key' => 'auth.email_verified', 'group' => 'auth', 'az' => 'Email doğrulandı!', 'ru' => 'Email подтверждён!', 'en' => 'Email Verified!'],
            ['key' => 'auth.email_verified_desc', 'group' => 'auth', 'az' => 'Hesabınız uğurla doğrulandı', 'ru' => 'Ваш аккаунт успешно подтверждён', 'en' => 'Your account has been successfully verified'],
            ['key' => 'auth.verification_sent', 'group' => 'auth', 'az' => 'Doğrulama emaili göndərildi', 'ru' => 'Письмо с подтверждением отправлено', 'en' => 'Verification Email Sent'],
            ['key' => 'auth.check_inbox', 'group' => 'auth', 'az' => 'Gelen qutunuzu yoxlayın', 'ru' => 'Проверьте входящие', 'en' => 'Check your inbox and click the link to verify your account'],
            ['key' => 'auth.verification_failed', 'group' => 'auth', 'az' => 'Doğrulama uğursuz oldu', 'ru' => 'Подтверждение не удалось', 'en' => 'Verification Failed'],
            ['key' => 'auth.verification_failed_desc', 'group' => 'auth', 'az' => 'Doğrulama linki etibarsız və ya müddəti bitib', 'ru' => 'Ссылка недействительна или устарела', 'en' => 'The verification link is invalid or has expired'],
            ['key' => 'auth.resend_verification', 'group' => 'auth', 'az' => 'Doğrulama emailini yenidən göndər', 'ru' => 'Повторно отправить письмо', 'en' => 'Resend Verification Email'],
            ['key' => 'auth.back_to_login', 'group' => 'auth', 'az' => 'Girişə qayıt', 'ru' => 'Назад ко входу', 'en' => 'Back to Login'],
            ['key' => 'auth.go_to_dashboard', 'group' => 'auth', 'az' => 'İdarə panelinə keç', 'ru' => 'Перейти на панель', 'en' => 'Go to Dashboard'],
            ['key' => 'auth.first_name', 'group' => 'auth', 'az' => 'Ad', 'ru' => 'Имя', 'en' => 'First name'],
            ['key' => 'auth.last_name', 'group' => 'auth', 'az' => 'Soyad', 'ru' => 'Фамилия', 'en' => 'Last name'],
            ['key' => 'auth.phone', 'group' => 'auth', 'az' => 'Telefon', 'ru' => 'Телефон', 'en' => 'Phone'],
            ['key' => 'auth.school', 'group' => 'auth', 'az' => 'Məktəb', 'ru' => 'Школа', 'en' => 'School'],
            ['key' => 'auth.select_school', 'group' => 'auth', 'az' => 'Məktəb seçin', 'ru' => 'Выберите школу', 'en' => 'Select school'],
            ['key' => 'auth.register_as_teacher', 'group' => 'auth', 'az' => 'Müəllim kimi qeydiyyat', 'ru' => 'Регистрация как учитель', 'en' => 'Register as Teacher'],
            ['key' => 'auth.register_as_parent', 'group' => 'auth', 'az' => 'Valideyn kimi qeydiyyat', 'ru' => 'Регистрация как родитель', 'en' => 'Register as Parent'],
            ['key' => 'auth.child_username', 'group' => 'auth', 'az' => 'Uşağın istifadəçi adı', 'ru' => 'Имя пользователя ребёнка', 'en' => 'Child username'],

            // ─── Common ───────────────────────────────────────────────────────
            ['key' => 'common.save', 'group' => 'common', 'az' => 'Saxla', 'ru' => 'Сохранить', 'en' => 'Save'],
            ['key' => 'common.cancel', 'group' => 'common', 'az' => 'Ləğv et', 'ru' => 'Отмена', 'en' => 'Cancel'],
            ['key' => 'common.delete', 'group' => 'common', 'az' => 'Sil', 'ru' => 'Удалить', 'en' => 'Delete'],
            ['key' => 'common.edit', 'group' => 'common', 'az' => 'Redaktə et', 'ru' => 'Редактировать', 'en' => 'Edit'],
            ['key' => 'common.create', 'group' => 'common', 'az' => 'Yarat', 'ru' => 'Создать', 'en' => 'Create'],
            ['key' => 'common.update', 'group' => 'common', 'az' => 'Yenilə', 'ru' => 'Обновить', 'en' => 'Update'],
            ['key' => 'common.add', 'group' => 'common', 'az' => 'Əlavə et', 'ru' => 'Добавить', 'en' => 'Add'],
            ['key' => 'common.remove', 'group' => 'common', 'az' => 'Çıxar', 'ru' => 'Удалить', 'en' => 'Remove'],
            ['key' => 'common.search', 'group' => 'common', 'az' => 'Axtar', 'ru' => 'Поиск', 'en' => 'Search'],
            ['key' => 'common.filter', 'group' => 'common', 'az' => 'Filtr', 'ru' => 'Фильтр', 'en' => 'Filter'],
            ['key' => 'common.export', 'group' => 'common', 'az' => 'İxrac et', 'ru' => 'Экспорт', 'en' => 'Export'],
            ['key' => 'common.import', 'group' => 'common', 'az' => 'İdxal et', 'ru' => 'Импорт', 'en' => 'Import'],
            ['key' => 'common.loading', 'group' => 'common', 'az' => 'Yüklənir...', 'ru' => 'Загрузка...', 'en' => 'Loading...'],
            ['key' => 'common.no_data', 'group' => 'common', 'az' => 'Məlumat yoxdur', 'ru' => 'Нет данных', 'en' => 'No data'],
            ['key' => 'common.confirm_delete', 'group' => 'common', 'az' => 'Silməyə əminsinizmi?', 'ru' => 'Вы уверены?', 'en' => 'Are you sure you want to delete?'],
            ['key' => 'common.success', 'group' => 'common', 'az' => 'Uğurlu', 'ru' => 'Успешно', 'en' => 'Success'],
            ['key' => 'common.error', 'group' => 'common', 'az' => 'Xəta', 'ru' => 'Ошибка', 'en' => 'Error'],
            ['key' => 'common.all', 'group' => 'common', 'az' => 'Hamısı', 'ru' => 'Все', 'en' => 'All'],
            ['key' => 'common.back', 'group' => 'common', 'az' => 'Geri', 'ru' => 'Назад', 'en' => 'Back'],
            ['key' => 'common.go_back', 'group' => 'common', 'az' => 'Geri qayıt', 'ru' => 'Назад', 'en' => 'Go Back'],
            ['key' => 'common.hide', 'group' => 'common', 'az' => 'Gizlət', 'ru' => 'Скрыть', 'en' => 'Hide'],
            ['key' => 'common.show', 'group' => 'common', 'az' => 'Göstər', 'ru' => 'Показать', 'en' => 'Show'],
            ['key' => 'common.active', 'group' => 'common', 'az' => 'Aktiv', 'ru' => 'Активный', 'en' => 'Active'],
            ['key' => 'common.inactive', 'group' => 'common', 'az' => 'Aktiv deyil', 'ru' => 'Неактивный', 'en' => 'Inactive'],
            ['key' => 'common.enabled', 'group' => 'common', 'az' => 'Aktiv', 'ru' => 'Включено', 'en' => 'Enabled'],
            ['key' => 'common.disabled', 'group' => 'common', 'az' => 'Deaktiv', 'ru' => 'Отключено', 'en' => 'Disabled'],
            ['key' => 'common.optional', 'group' => 'common', 'az' => 'İstəyə bağlı', 'ru' => 'Необязательно', 'en' => 'Optional'],
            ['key' => 'common.required', 'group' => 'common', 'az' => 'Məcburi', 'ru' => 'Обязательно', 'en' => 'Required'],
            ['key' => 'common.language', 'group' => 'common', 'az' => 'Dil', 'ru' => 'Язык', 'en' => 'Language'],
            ['key' => 'common.description', 'group' => 'common', 'az' => 'Təsvir', 'ru' => 'Описание', 'en' => 'Description'],
            ['key' => 'common.name', 'group' => 'common', 'az' => 'Ad', 'ru' => 'Название', 'en' => 'Name'],
            ['key' => 'common.status', 'group' => 'common', 'az' => 'Status', 'ru' => 'Статус', 'en' => 'Status'],
            ['key' => 'common.actions', 'group' => 'common', 'az' => 'Əməliyyatlar', 'ru' => 'Действия', 'en' => 'Actions'],
            ['key' => 'common.close', 'group' => 'common', 'az' => 'Bağla', 'ru' => 'Закрыть', 'en' => 'Close'],
            ['key' => 'common.confirm', 'group' => 'common', 'az' => 'Təsdiqlə', 'ru' => 'Подтвердить', 'en' => 'Confirm'],
            ['key' => 'common.select', 'group' => 'common', 'az' => 'Seçin', 'ru' => 'Выберите', 'en' => 'Select'],
            ['key' => 'common.today', 'group' => 'common', 'az' => 'Bu gün', 'ru' => 'Сегодня', 'en' => 'Today'],
            ['key' => 'common.this_week', 'group' => 'common', 'az' => 'Bu həftə', 'ru' => 'Эта неделя', 'en' => 'week'],
            ['key' => 'common.this_month', 'group' => 'common', 'az' => 'Bu ay', 'ru' => 'Этот месяц', 'en' => 'month'],
            ['key' => 'common.this_year', 'group' => 'common', 'az' => 'Bu il', 'ru' => 'Этот год', 'en' => 'year'],
            ['key' => 'common.from', 'group' => 'common', 'az' => 'Başlanğıc', 'ru' => 'От', 'en' => 'From'],
            ['key' => 'common.to', 'group' => 'common', 'az' => 'Son', 'ru' => 'До', 'en' => 'To'],
            ['key' => 'common.submit', 'group' => 'common', 'az' => 'Göndər', 'ru' => 'Отправить', 'en' => 'Submit'],
            ['key' => 'common.saving', 'group' => 'common', 'az' => 'Saxlanılır...', 'ru' => 'Сохранение...', 'en' => 'Saving...'],
            ['key' => 'common.deleting', 'group' => 'common', 'az' => 'Silinir...', 'ru' => 'Удаление...', 'en' => 'Deleting...'],
            ['key' => 'common.role', 'group' => 'common', 'az' => 'Rol', 'ru' => 'Роль', 'en' => 'Role'],
            ['key' => 'common.permissions', 'group' => 'common', 'az' => 'İcazələr', 'ru' => 'Разрешения', 'en' => 'Permissions'],
            ['key' => 'common.never', 'group' => 'common', 'az' => 'Heç vaxt', 'ru' => 'Никогда', 'en' => 'Never'],

            // ─── Navigation ───────────────────────────────────────────────────
            ['key' => 'nav.dashboard', 'group' => 'navigation', 'az' => 'İdarə paneli', 'ru' => 'Панель управления', 'en' => 'Dashboard'],
            ['key' => 'nav.play', 'group' => 'navigation', 'az' => 'Oyna', 'ru' => 'Играть', 'en' => 'Play'],
            ['key' => 'nav.students', 'group' => 'navigation', 'az' => 'Şagirdlər', 'ru' => 'Ученики', 'en' => 'Students'],
            ['key' => 'nav.teachers', 'group' => 'navigation', 'az' => 'Müəllimlər', 'ru' => 'Учителя', 'en' => 'Teachers'],
            ['key' => 'nav.analytics', 'group' => 'navigation', 'az' => 'Analitika', 'ru' => 'Аналитика', 'en' => 'Analytics'],
            ['key' => 'nav.settings', 'group' => 'navigation', 'az' => 'Parametrlər', 'ru' => 'Настройки', 'en' => 'Settings'],
            ['key' => 'nav.achievements', 'group' => 'navigation', 'az' => 'Nailiyyətlər', 'ru' => 'Достижения', 'en' => 'Achievements'],
            ['key' => 'nav.leaderboard', 'group' => 'navigation', 'az' => 'Liderlik cədvəli', 'ru' => 'Таблица лидеров', 'en' => 'Leaderboard'],
            ['key' => 'nav.history', 'group' => 'navigation', 'az' => 'Tarixçə', 'ru' => 'История', 'en' => 'History'],
            ['key' => 'nav.competitions', 'group' => 'navigation', 'az' => 'Yarışmalar', 'ru' => 'Соревнования', 'en' => 'Competitions'],
            ['key' => 'nav.profile', 'group' => 'navigation', 'az' => 'Profil', 'ru' => 'Профиль', 'en' => 'Profile'],
            ['key' => 'nav.users', 'group' => 'navigation', 'az' => 'İstifadəçilər', 'ru' => 'Пользователи', 'en' => 'Users'],
            ['key' => 'nav.schools', 'group' => 'navigation', 'az' => 'Məktəblər', 'ru' => 'Школы', 'en' => 'Schools'],
            ['key' => 'nav.strings', 'group' => 'navigation', 'az' => 'Sistem mətnləri', 'ru' => 'Системные тексты', 'en' => 'System Strings'],
            ['key' => 'nav.roles', 'group' => 'navigation', 'az' => 'Rollar', 'ru' => 'Роли', 'en' => 'Roles'],
            ['key' => 'nav.texts', 'group' => 'navigation', 'az' => 'Mətnlər', 'ru' => 'Тексты', 'en' => 'Texts'],
            ['key' => 'nav.words', 'group' => 'navigation', 'az' => 'Söz siyahıları', 'ru' => 'Списки слов', 'en' => 'Word Lists'],
            ['key' => 'nav.audit_logs', 'group' => 'navigation', 'az' => 'Audit jurnalı', 'ru' => 'Журнал аудита', 'en' => 'Audit Logs'],
            ['key' => 'nav.children', 'group' => 'navigation', 'az' => 'Uşaqlarım', 'ru' => 'Мои дети', 'en' => 'My Children'],

            // ─── Game ─────────────────────────────────────────────────────────
            ['key' => 'game.start', 'group' => 'game', 'az' => 'Başla', 'ru' => 'Начать', 'en' => 'Start'],
            ['key' => 'game.finish', 'group' => 'game', 'az' => 'Bitir', 'ru' => 'Завершить', 'en' => 'Finish'],
            ['key' => 'game.pause', 'group' => 'game', 'az' => 'Dayandır', 'ru' => 'Пауза', 'en' => 'Pause'],
            ['key' => 'game.wpm', 'group' => 'game', 'az' => 'Söz/dəq', 'ru' => 'Слов/мин', 'en' => 'WPM'],
            ['key' => 'game.select_mode', 'group' => 'game', 'az' => 'Rejimi seçin', 'ru' => 'Выберите режим', 'en' => 'Select mode'],
            ['key' => 'game.select_duration', 'group' => 'game', 'az' => 'Müddəti seçin', 'ru' => 'Выберите длительность', 'en' => 'Select duration'],
            ['key' => 'game.random_words', 'group' => 'game', 'az' => 'Təsadüfi sözlər', 'ru' => 'Случайные слова', 'en' => 'Random words'],
            ['key' => 'game.text_reading', 'group' => 'game', 'az' => 'Mətn oxuma', 'ru' => 'Чтение текста', 'en' => 'Text reading'],
            ['key' => 'game.sentence_reading', 'group' => 'game', 'az' => 'Cümlə oxuma', 'ru' => 'Чтение предложений', 'en' => 'Sentence reading'],
            ['key' => 'game.memory', 'group' => 'game', 'az' => 'Yaddaş', 'ru' => 'Память', 'en' => 'Memory'],
            ['key' => 'game.ai_mode', 'group' => 'game', 'az' => 'AI rejimi', 'ru' => 'Режим ИИ', 'en' => 'AI mode'],
            ['key' => 'game.finished', 'group' => 'game', 'az' => 'Oyun bitdi! :wpm söz/dəqiqə', 'ru' => 'Игра завершена! :wpm слов/мин', 'en' => 'Game finished! :wpm WPM'],
            ['key' => 'game.start_failed', 'group' => 'game', 'az' => 'Oyun başladıla bilmədi', 'ru' => 'Не удалось начать игру', 'en' => 'Failed to start game'],
            ['key' => 'game.click_words', 'group' => 'game', 'az' => 'Sözlərə sırayla klikləyin', 'ru' => 'Нажимайте слова по порядку', 'en' => 'Click words in order'],
            ['key' => 'game.countdown', 'group' => 'game', 'az' => 'Hazır olun...', 'ru' => 'Приготовьтесь...', 'en' => 'Get ready...'],
            ['key' => 'game.results', 'group' => 'game', 'az' => 'Nəticə', 'ru' => 'Результат', 'en' => 'Results'],
            ['key' => 'game.play_again', 'group' => 'game', 'az' => 'Yenidən oyna', 'ru' => 'Играть снова', 'en' => 'Play again'],
            ['key' => 'game.accuracy', 'group' => 'game', 'az' => 'Dəqiqlik', 'ru' => 'Точность', 'en' => 'Accuracy'],
            ['key' => 'game.words_read', 'group' => 'game', 'az' => 'Oxunan sözlər', 'ru' => 'Прочитано слов', 'en' => 'Words read'],
            ['key' => 'game.time', 'group' => 'game', 'az' => 'Vaxt', 'ru' => 'Время', 'en' => 'Time'],
            ['key' => 'game.xp_earned', 'group' => 'game', 'az' => '+:xp XP qazandınız', 'ru' => '+:xp XP получено', 'en' => '+:xp XP earned'],
            ['key' => 'game.select_language', 'group' => 'game', 'az' => 'Dil seçin', 'ru' => 'Выберите язык', 'en' => 'Select language'],
            ['key' => 'game.select_difficulty', 'group' => 'game', 'az' => 'Çətinlik seçin', 'ru' => 'Выберите сложность', 'en' => 'Select difficulty'],

            // ─── Analytics ────────────────────────────────────────────────────
            ['key' => 'analytics.no_data', 'group' => 'analytics', 'az' => 'Məlumat yoxdur', 'ru' => 'Нет данных', 'en' => 'No data available'],
            ['key' => 'analytics.sessions', 'group' => 'analytics', 'az' => 'Sessiyalar', 'ru' => 'Сессии', 'en' => 'Sessions'],
            ['key' => 'analytics.wpm', 'group' => 'analytics', 'az' => 'Söz/dəq', 'ru' => 'Слов/мин', 'en' => 'WPM'],
            ['key' => 'analytics.avg_wpm', 'group' => 'analytics', 'az' => 'Ort. söz/dəq', 'ru' => 'Ср. слов/мин', 'en' => 'Avg WPM'],
            ['key' => 'analytics.best_wpm', 'group' => 'analytics', 'az' => 'Ən yaxşı söz/dəq', 'ru' => 'Лучший показатель', 'en' => 'Best WPM'],
            ['key' => 'analytics.wpm_trend', 'group' => 'analytics', 'az' => 'Söz/dəq trendi', 'ru' => 'Тренд слов/мин', 'en' => 'WPM Trend'],
            ['key' => 'analytics.daily_activity', 'group' => 'analytics', 'az' => 'Günlük aktivlik', 'ru' => 'Дневная активность', 'en' => 'Daily Activity'],
            ['key' => 'analytics.by_language', 'group' => 'analytics', 'az' => 'Dilə görə', 'ru' => 'По языку', 'en' => 'By Language'],
            ['key' => 'analytics.by_mode', 'group' => 'analytics', 'az' => 'Rejimə görə', 'ru' => 'По режиму', 'en' => 'By Game Mode'],
            ['key' => 'analytics.today', 'group' => 'analytics', 'az' => 'Bu gün', 'ru' => 'Сегодня', 'en' => 'Today'],
            ['key' => 'analytics.total_sessions', 'group' => 'analytics', 'az' => 'Cəmi sessiyalar', 'ru' => 'Всего сессий', 'en' => 'Total Sessions'],
            ['key' => 'analytics.overview', 'group' => 'analytics', 'az' => 'Ümumi baxış', 'ru' => 'Обзор', 'en' => 'Overview'],
            ['key' => 'analytics.my_stats', 'group' => 'analytics', 'az' => 'Mənim statistikam', 'ru' => 'Моя статистика', 'en' => 'My Stats'],
            ['key' => 'analytics.weakest_words', 'group' => 'analytics', 'az' => 'Ən zəif sözlər', 'ru' => 'Слабые слова', 'en' => 'Weakest Words'],
            ['key' => 'analytics.export', 'group' => 'analytics', 'az' => 'İxrac et', 'ru' => 'Экспорт', 'en' => 'Export'],

            // ─── Gamification ─────────────────────────────────────────────────
            ['key' => 'gamification.level', 'group' => 'gamification', 'az' => 'Səviyyə', 'ru' => 'Уровень', 'en' => 'Level'],
            ['key' => 'gamification.xp', 'group' => 'gamification', 'az' => 'Təcrübə xalı', 'ru' => 'Очки опыта', 'en' => 'XP'],
            ['key' => 'gamification.to_next', 'group' => 'gamification', 'az' => 'növbəti səviyyəyə', 'ru' => 'до следующего', 'en' => 'to next'],
            ['key' => 'gamification.streak', 'group' => 'gamification', 'az' => ':days günlük seriya!', 'ru' => 'Серия :days дней!', 'en' => ':days day streak!'],
            ['key' => 'gamification.achievements', 'group' => 'gamification', 'az' => 'Nailiyyətlər', 'ru' => 'Достижения', 'en' => 'Achievements'],
            ['key' => 'gamification.recent_achievements', 'group' => 'gamification', 'az' => 'Son nailiyyətlər', 'ru' => 'Последние достижения', 'en' => 'Recent Achievements'],
            ['key' => 'gamification.locked', 'group' => 'gamification', 'az' => 'Kilidli', 'ru' => 'Заблокировано', 'en' => 'Locked'],
            ['key' => 'gamification.earned', 'group' => 'gamification', 'az' => 'Qazanıldı', 'ru' => 'Получено', 'en' => 'Earned'],
            ['key' => 'gamification.rank', 'group' => 'gamification', 'az' => 'Sıra', 'ru' => 'Место', 'en' => 'Rank'],
            ['key' => 'gamification.level_up', 'group' => 'gamification', 'az' => 'Səviyyə yüksəldi! Səviyyə :level', 'ru' => 'Уровень повышен! Уровень :level', 'en' => 'Level up! Level :level'],

            // ─── Leaderboard ──────────────────────────────────────────────────
            ['key' => 'leaderboard.global', 'group' => 'leaderboard', 'az' => 'Ümumi', 'ru' => 'Глобальный', 'en' => 'Global'],
            ['key' => 'leaderboard.school', 'group' => 'leaderboard', 'az' => 'Məktəb', 'ru' => 'Школа', 'en' => 'School'],
            ['key' => 'leaderboard.class', 'group' => 'leaderboard', 'az' => 'Sinif', 'ru' => 'Класс', 'en' => 'Class'],
            ['key' => 'leaderboard.by_xp', 'group' => 'leaderboard', 'az' => 'XP-yə görə', 'ru' => 'По XP', 'en' => 'By XP'],
            ['key' => 'leaderboard.by_wpm', 'group' => 'leaderboard', 'az' => 'Sürətə görə', 'ru' => 'По скорости', 'en' => 'By WPM'],
            ['key' => 'leaderboard.by_sessions', 'group' => 'leaderboard', 'az' => 'Sessiyalara görə', 'ru' => 'По сессиям', 'en' => 'By Sessions'],
            ['key' => 'leaderboard.you', 'group' => 'leaderboard', 'az' => 'Siz', 'ru' => 'Вы', 'en' => 'You'],
            ['key' => 'leaderboard.empty', 'group' => 'leaderboard', 'az' => 'Hələ ki liderlik cədvəli yoxdur', 'ru' => 'Таблица лидеров пуста', 'en' => 'No leaderboard entries yet'],

            // ─── Profile ──────────────────────────────────────────────────────
            ['key' => 'profile.title', 'group' => 'profile', 'az' => 'Profil', 'ru' => 'Профиль', 'en' => 'Profile'],
            ['key' => 'profile.avatar', 'group' => 'profile', 'az' => 'Avatar', 'ru' => 'Аватар', 'en' => 'Avatar'],
            ['key' => 'profile.change_avatar', 'group' => 'profile', 'az' => 'Avatarı dəyiş', 'ru' => 'Изменить аватар', 'en' => 'Change avatar'],
            ['key' => 'profile.personal_info', 'group' => 'profile', 'az' => 'Şəxsi məlumatlar', 'ru' => 'Личные данные', 'en' => 'Personal info'],
            ['key' => 'profile.change_password', 'group' => 'profile', 'az' => 'Şifrəni dəyiş', 'ru' => 'Изменить пароль', 'en' => 'Change password'],
            ['key' => 'profile.current_password', 'group' => 'profile', 'az' => 'Cari şifrə', 'ru' => 'Текущий пароль', 'en' => 'Current password'],
            ['key' => 'profile.new_password', 'group' => 'profile', 'az' => 'Yeni şifrə', 'ru' => 'Новый пароль', 'en' => 'New password'],
            ['key' => 'profile.updated', 'group' => 'profile', 'az' => 'Profil yeniləndi', 'ru' => 'Профиль обновлён', 'en' => 'Profile updated'],
            ['key' => 'profile.password_updated', 'group' => 'profile', 'az' => 'Şifrə yeniləndi', 'ru' => 'Пароль обновлён', 'en' => 'Password updated'],
            ['key' => 'profile.avatar_uploaded', 'group' => 'profile', 'az' => 'Avatar yükləndi', 'ru' => 'Аватар загружен', 'en' => 'Avatar uploaded'],
            ['key' => 'profile.preferred_language', 'group' => 'profile', 'az' => 'Üstünlük verilən dil', 'ru' => 'Предпочтительный язык', 'en' => 'Preferred language'],
            ['key' => 'profile.my_stats', 'group' => 'profile', 'az' => 'Mənim statistikam', 'ru' => 'Моя статистика', 'en' => 'My Stats'],

            // ─── Notifications ────────────────────────────────────────────────
            ['key' => 'notifications.title', 'group' => 'notifications', 'az' => 'Bildirişlər', 'ru' => 'Уведомления', 'en' => 'Notifications'],
            ['key' => 'notifications.empty', 'group' => 'notifications', 'az' => 'Bildiriş yoxdur', 'ru' => 'Нет уведомлений', 'en' => 'No notifications'],
            ['key' => 'notifications.mark_all_read', 'group' => 'notifications', 'az' => 'Hamısını oxunmuş et', 'ru' => 'Отметить все прочитанными', 'en' => 'Mark all as read'],
            ['key' => 'notifications.view_all', 'group' => 'notifications', 'az' => 'Hamısına bax', 'ru' => 'Посмотреть все', 'en' => 'View all'],
            ['key' => 'notifications.achievement_earned', 'group' => 'notifications', 'az' => 'Nailiyyət qazandınız: :name', 'ru' => 'Достижение получено: :name', 'en' => 'Achievement earned: :name'],
            ['key' => 'notifications.streak_milestone', 'group' => 'notifications', 'az' => ':days günlük seriya!', 'ru' => 'Серия :days дней!', 'en' => ':days day streak!'],
            ['key' => 'notifications.level_up', 'group' => 'notifications', 'az' => 'Səviyyə :level-ə yüksəldiniz!', 'ru' => 'Вы достигли уровня :level!', 'en' => 'You reached level :level!'],

            // ─── Admin ────────────────────────────────────────────────────────
            ['key' => 'admin.users_desc', 'group' => 'admin', 'az' => 'Platforma istifadəçilərini idarə edin', 'ru' => 'Управление пользователями платформы', 'en' => 'Manage platform users'],
            ['key' => 'admin.strings_desc', 'group' => 'admin', 'az' => 'UI mətnlərini idarə edin', 'ru' => 'Управление текстами интерфейса', 'en' => 'Manage UI strings'],
            ['key' => 'admin.schools_desc', 'group' => 'admin', 'az' => 'Məktəb və sinifləri idarə edin', 'ru' => 'Управление школами и классами', 'en' => 'Manage schools and classes'],
            ['key' => 'admin.roles_desc', 'group' => 'admin', 'az' => 'Rol və icazələri idarə edin', 'ru' => 'Управление ролями и разрешениями', 'en' => 'Manage roles and permissions'],
            ['key' => 'admin.texts_desc', 'group' => 'admin', 'az' => 'Oxuma mətnlərini idarə edin', 'ru' => 'Управление текстами для чтения', 'en' => 'Manage reading texts'],
            ['key' => 'admin.words_desc', 'group' => 'admin', 'az' => 'Məşq söz siyahılarını idarə edin', 'ru' => 'Управление списками слов', 'en' => 'Manage word lists used in reading exercises'],
            ['key' => 'admin.settings_desc', 'group' => 'admin', 'az' => 'Platformanın ümumi parametrləri', 'ru' => 'Общие настройки платформы', 'en' => 'General platform settings'],
            ['key' => 'admin.competitions_desc', 'group' => 'admin', 'az' => 'Yarışmaları idarə edin', 'ru' => 'Управление соревнованиями', 'en' => 'Manage competitions'],
            ['key' => 'admin.audit_logs_desc', 'group' => 'admin', 'az' => 'Sistem fəaliyyətini izləyin', 'ru' => 'Мониторинг активности системы', 'en' => 'Monitor system activity'],
            ['key' => 'admin.analytics_desc', 'group' => 'admin', 'az' => 'Platforma analitikasına baxın', 'ru' => 'Просмотр аналитики платформы', 'en' => 'View platform-wide analytics'],
            ['key' => 'admin.total_users', 'group' => 'admin', 'az' => 'Cəmi istifadəçilər', 'ru' => 'Всего пользователей', 'en' => 'Total Users'],
            ['key' => 'admin.active_users', 'group' => 'admin', 'az' => 'Aktiv istifadəçilər', 'ru' => 'Активные пользователи', 'en' => 'Active Users'],
            ['key' => 'admin.total_sessions', 'group' => 'admin', 'az' => 'Cəmi sessiyalar', 'ru' => 'Всего сессий', 'en' => 'Total Sessions'],
            ['key' => 'admin.total_schools', 'group' => 'admin', 'az' => 'Cəmi məktəblər', 'ru' => 'Всего школ', 'en' => 'Total Schools'],
            ['key' => 'admin.invite_user', 'group' => 'admin', 'az' => 'İstifadəçi dəvət et', 'ru' => 'Пригласить пользователя', 'en' => 'Invite User'],
            ['key' => 'admin.add_school', 'group' => 'admin', 'az' => 'Məktəb əlavə et', 'ru' => 'Добавить школу', 'en' => 'Add School'],
            ['key' => 'admin.manage_roles', 'group' => 'admin', 'az' => 'Rolları idarə et', 'ru' => 'Управление ролями', 'en' => 'Manage Roles'],
            ['key' => 'admin.view_logs', 'group' => 'admin', 'az' => 'Jurnala bax', 'ru' => 'Просмотр журнала', 'en' => 'View Logs'],
            ['key' => 'admin.system_settings', 'group' => 'admin', 'az' => 'Sistem parametrləri', 'ru' => 'Системные настройки', 'en' => 'System Settings'],
            ['key' => 'admin.no_users', 'group' => 'admin', 'az' => 'İstifadəçi tapılmadı', 'ru' => 'Пользователи не найдены', 'en' => 'No users found'],
            ['key' => 'admin.deactivate', 'group' => 'admin', 'az' => 'Deaktiv et', 'ru' => 'Деактивировать', 'en' => 'Deactivate'],
            ['key' => 'admin.activate', 'group' => 'admin', 'az' => 'Aktiv et', 'ru' => 'Активировать', 'en' => 'Activate'],

            // ─── Teacher ──────────────────────────────────────────────────────
            ['key' => 'teacher.students_desc', 'group' => 'teacher', 'az' => 'Sinfinizin şagirdlərini izləyin', 'ru' => 'Отслеживайте учеников вашего класса', 'en' => "Monitor your class's students"],
            ['key' => 'teacher.analytics_desc', 'group' => 'teacher', 'az' => 'Sinfinizin performans icmalı', 'ru' => 'Обзор успеваемости вашего класса', 'en' => "Your class's performance overview"],
            ['key' => 'teacher.total_students', 'group' => 'teacher', 'az' => 'Şagirdlər', 'ru' => 'Ученики', 'en' => 'Students'],
            ['key' => 'teacher.active_today', 'group' => 'teacher', 'az' => 'Bu gün aktiv', 'ru' => 'Активны сегодня', 'en' => 'Active Today'],
            ['key' => 'teacher.top_students', 'group' => 'teacher', 'az' => 'Ən yaxşı şagirdlər', 'ru' => 'Лучшие ученики', 'en' => 'Top Students'],
            ['key' => 'teacher.no_students', 'group' => 'teacher', 'az' => 'Hələ şagird yoxdur', 'ru' => 'Учеников пока нет', 'en' => 'No students yet'],

            // ─── Parent ───────────────────────────────────────────────────────
            ['key' => 'parent.children_desc', 'group' => 'parent', 'az' => 'Uşaqlarınızın inkişafına ətraflı baxış', 'ru' => 'Подробный просмотр прогресса ваших детей', 'en' => "Detailed view of your children's progress"],
            ['key' => 'parent.no_children', 'group' => 'parent', 'az' => 'Hesabınıza bağlı uşaq yoxdur', 'ru' => 'Нет детей, привязанных к вашему аккаунту', 'en' => 'No children linked to your account'],
            ['key' => 'parent.view_progress', 'group' => 'parent', 'az' => 'Tam hesabat', 'ru' => 'Полный отчёт', 'en' => 'Full Report'],
            ['key' => 'parent.child_not_found', 'group' => 'parent', 'az' => 'Uşaq tapılmadı', 'ru' => 'Ребёнок не найден', 'en' => 'Child not found'],

            // ─── Competitions ─────────────────────────────────────────────────
            ['key' => 'competitions.desc', 'group' => 'competitions', 'az' => 'Başqaları ilə yarışın və reytinqdə yuxarı qalxın', 'ru' => 'Соревнуйтесь с другими и поднимайтесь в рейтинге', 'en' => 'Compete with others and climb the rankings'],
            ['key' => 'competitions.active', 'group' => 'competitions', 'az' => 'Aktiv', 'ru' => 'Активные', 'en' => 'Active'],
            ['key' => 'competitions.upcoming', 'group' => 'competitions', 'az' => 'Gələcək', 'ru' => 'Предстоящие', 'en' => 'Upcoming'],
            ['key' => 'competitions.ended', 'group' => 'competitions', 'az' => 'Başa çatıb', 'ru' => 'Завершённые', 'en' => 'Ended'],
            ['key' => 'competitions.none', 'group' => 'competitions', 'az' => 'Hal-hazırda yarışma yoxdur', 'ru' => 'Соревнований пока нет', 'en' => 'No competitions available right now'],
            ['key' => 'competitions.join', 'group' => 'competitions', 'az' => 'Qoşul', 'ru' => 'Присоединиться', 'en' => 'Join'],
            ['key' => 'competitions.joined', 'group' => 'competitions', 'az' => 'Yarışmaya qoşuldunuz!', 'ru' => 'Вы присоединились к соревнованию!', 'en' => 'Joined competition!'],
            ['key' => 'competitions.joined_label', 'group' => 'competitions', 'az' => 'Qoşuldu', 'ru' => 'Присоединился', 'en' => 'Joined'],
            ['key' => 'competitions.join_error', 'group' => 'competitions', 'az' => 'Yarışmaya qoşulmaq mümkün olmadı', 'ru' => 'Не удалось присоединиться', 'en' => 'Could not join competition'],
            ['key' => 'competitions.participants', 'group' => 'competitions', 'az' => 'iştirakçı', 'ru' => 'участников', 'en' => 'participants'],
            ['key' => 'competitions.starts_in', 'group' => 'competitions', 'az' => 'Başlayır', 'ru' => 'Начнётся', 'en' => 'Starts'],
            ['key' => 'competitions.ends_in', 'group' => 'competitions', 'az' => 'Bitir', 'ru' => 'Заканчивается', 'en' => 'Ends'],
            ['key' => 'competitions.ended_ago', 'group' => 'competitions', 'az' => 'Bitdi', 'ru' => 'Завершилось', 'en' => 'Ended'],
            ['key' => 'competitions.no_scores', 'group' => 'competitions', 'az' => 'Hələ nəticə yoxdur', 'ru' => 'Результатов пока нет', 'en' => 'No scores yet'],
            ['key' => 'competitions.view_board', 'group' => 'competitions', 'az' => 'Liderlik', 'ru' => 'Рейтинг', 'en' => 'Leaderboard'],
            ['key' => 'competitions.title', 'group' => 'competitions', 'az' => 'Başlıq', 'ru' => 'Заголовок', 'en' => 'Title'],
            ['key' => 'competitions.starts_at', 'group' => 'competitions', 'az' => 'Başlama vaxtı', 'ru' => 'Дата начала', 'en' => 'Starts at'],
            ['key' => 'competitions.ends_at', 'group' => 'competitions', 'az' => 'Bitmə vaxtı', 'ru' => 'Дата окончания', 'en' => 'Ends at'],
            ['key' => 'competitions.max_participants', 'group' => 'competitions', 'az' => 'Maks. iştirakçı', 'ru' => 'Макс. участников', 'en' => 'Max participants'],
            ['key' => 'competitions.created', 'group' => 'competitions', 'az' => 'Yarışma yaradıldı', 'ru' => 'Соревнование создано', 'en' => 'Competition created'],
            ['key' => 'competitions.deleted', 'group' => 'competitions', 'az' => 'Yarışma silindi', 'ru' => 'Соревнование удалено', 'en' => 'Competition deleted'],
            ['key' => 'competitions.delete_confirm', 'group' => 'competitions', 'az' => 'Bu yarışmanı silmək istəyirsinizmi?', 'ru' => 'Удалить это соревнование?', 'en' => 'Delete this competition?'],
            ['key' => 'competitions.new', 'group' => 'competitions', 'az' => 'Yeni yarışma', 'ru' => 'Новое соревнование', 'en' => 'New Competition'],

            // ─── Texts ────────────────────────────────────────────────────────
            ['key' => 'texts.title', 'group' => 'texts', 'az' => 'Mətnlər', 'ru' => 'Тексты', 'en' => 'Texts'],
            ['key' => 'texts.new', 'group' => 'texts', 'az' => 'Yeni mətn', 'ru' => 'Новый текст', 'en' => 'New Text'],
            ['key' => 'texts.title_label', 'group' => 'texts', 'az' => 'Başlıq', 'ru' => 'Заголовок', 'en' => 'Title'],
            ['key' => 'texts.content', 'group' => 'texts', 'az' => 'Mətn', 'ru' => 'Текст', 'en' => 'Content'],
            ['key' => 'texts.difficulty', 'group' => 'texts', 'az' => 'Çətinlik', 'ru' => 'Сложность', 'en' => 'Difficulty'],
            ['key' => 'texts.beginner', 'group' => 'texts', 'az' => 'Başlanğıc', 'ru' => 'Начинающий', 'en' => 'Beginner'],
            ['key' => 'texts.intermediate', 'group' => 'texts', 'az' => 'Orta', 'ru' => 'Средний', 'en' => 'Intermediate'],
            ['key' => 'texts.advanced', 'group' => 'texts', 'az' => 'İrəliləmiş', 'ru' => 'Продвинутый', 'en' => 'Advanced'],
            ['key' => 'texts.word_count', 'group' => 'texts', 'az' => 'Söz sayı', 'ru' => 'Кол-во слов', 'en' => 'Word count'],
            ['key' => 'texts.created', 'group' => 'texts', 'az' => 'Mətn yaradıldı', 'ru' => 'Текст создан', 'en' => 'Text created'],
            ['key' => 'texts.updated', 'group' => 'texts', 'az' => 'Mətn yeniləndi', 'ru' => 'Текст обновлён', 'en' => 'Text updated'],
            ['key' => 'texts.deleted', 'group' => 'texts', 'az' => 'Mətn silindi', 'ru' => 'Текст удалён', 'en' => 'Text deleted'],
            ['key' => 'texts.delete_confirm', 'group' => 'texts', 'az' => 'Bu mətni silmək istəyirsinizmi?', 'ru' => 'Удалить этот текст?', 'en' => 'Delete this text?'],
            ['key' => 'texts.none', 'group' => 'texts', 'az' => 'Mətn tapılmadı', 'ru' => 'Тексты не найдены', 'en' => 'No texts found'],

            // ─── Words ────────────────────────────────────────────────────────
            ['key' => 'words.new_list', 'group' => 'words', 'az' => 'Yeni söz siyahısı', 'ru' => 'Новый список слов', 'en' => 'New List'],
            ['key' => 'words.list_name', 'group' => 'words', 'az' => 'Siyahı adı', 'ru' => 'Название списка', 'en' => 'List Name'],
            ['key' => 'words.list_name_placeholder', 'group' => 'words', 'az' => 'məs. Başlanğıc Azərbaycan', 'ru' => 'напр. Начинающий Азербайджан', 'en' => 'e.g. Beginner Azerbaijani'],
            ['key' => 'words.difficulty', 'group' => 'words', 'az' => 'Çətinlik', 'ru' => 'Сложность', 'en' => 'Difficulty'],
            ['key' => 'words.beginner', 'group' => 'words', 'az' => 'Başlanğıc', 'ru' => 'Начинающий', 'en' => 'Beginner'],
            ['key' => 'words.intermediate', 'group' => 'words', 'az' => 'Orta', 'ru' => 'Средний', 'en' => 'Intermediate'],
            ['key' => 'words.advanced', 'group' => 'words', 'az' => 'İrəliləmiş', 'ru' => 'Продвинутый', 'en' => 'Advanced'],
            ['key' => 'words.words', 'group' => 'words', 'az' => 'söz', 'ru' => 'слов', 'en' => 'words'],
            ['key' => 'words.manage_words', 'group' => 'words', 'az' => 'Sözlər', 'ru' => 'Слова', 'en' => 'Words'],
            ['key' => 'words.new_word_placeholder', 'group' => 'words', 'az' => 'Söz əlavə et...', 'ru' => 'Добавить слово...', 'en' => 'Add a word...'],
            ['key' => 'words.word_added', 'group' => 'words', 'az' => 'Söz əlavə edildi', 'ru' => 'Слово добавлено', 'en' => 'Word added'],
            ['key' => 'words.no_words', 'group' => 'words', 'az' => 'Hələ söz yoxdur', 'ru' => 'Слов пока нет', 'en' => 'No words yet. Add some above.'],
            ['key' => 'words.list_created', 'group' => 'words', 'az' => 'Söz siyahısı yaradıldı', 'ru' => 'Список слов создан', 'en' => 'Word list created'],
            ['key' => 'words.list_deleted', 'group' => 'words', 'az' => 'Söz siyahısı silindi', 'ru' => 'Список слов удалён', 'en' => 'Word list deleted'],
            ['key' => 'words.delete_list_title', 'group' => 'words', 'az' => 'Söz siyahısını silin?', 'ru' => 'Удалить список слов?', 'en' => 'Delete Word List?'],
            ['key' => 'words.delete_list_desc', 'group' => 'words', 'az' => 'Bu siyahı və bütün sözlər daimi silinəcək', 'ru' => 'Список и все слова будут удалены навсегда', 'en' => 'This will permanently delete the list and all its words'],
            ['key' => 'words.no_lists', 'group' => 'words', 'az' => 'Söz siyahısı tapılmadı', 'ru' => 'Списки слов не найдены', 'en' => 'No word lists found'],

            // ─── Settings ─────────────────────────────────────────────────────
            ['key' => 'settings.maintenance_mode', 'group' => 'settings', 'az' => 'Texniki xidmət rejimi', 'ru' => 'Режим обслуживания', 'en' => 'Maintenance mode'],
            ['key' => 'settings.maintenance_desc', 'group' => 'settings', 'az' => 'Sayt texniki xidmət üçün bağlanacaq', 'ru' => 'Сайт будет закрыт для обслуживания', 'en' => 'Site will be closed for maintenance'],
            ['key' => 'settings.registration_enabled', 'group' => 'settings', 'az' => 'Qeydiyyat açıq', 'ru' => 'Регистрация открыта', 'en' => 'Registration enabled'],
            ['key' => 'settings.registration_desc', 'group' => 'settings', 'az' => 'Yeni istifadəçilərin qeydiyyatına icazə ver', 'ru' => 'Разрешить регистрацию новых пользователей', 'en' => 'Allow new user registrations'],
            ['key' => 'settings.game_modes', 'group' => 'settings', 'az' => 'Oyun rejimləri', 'ru' => 'Игровые режимы', 'en' => 'Game modes'],
            ['key' => 'settings.game_modes_desc', 'group' => 'settings', 'az' => 'Aktiv oyun rejimlərini seçin', 'ru' => 'Выберите активные игровые режимы', 'en' => 'Select active game modes'],
            ['key' => 'settings.token_expiry', 'group' => 'settings', 'az' => 'Token müddəti (dəqiqə)', 'ru' => 'Срок действия токена (мин)', 'en' => 'Token expiry (minutes)'],
            ['key' => 'settings.saved', 'group' => 'settings', 'az' => 'Parametrlər yadda saxlanıldı', 'ru' => 'Настройки сохранены', 'en' => 'Settings saved'],
            ['key' => 'settings.save_error', 'group' => 'settings', 'az' => 'Yadda saxlamaq uğursuz oldu', 'ru' => 'Не удалось сохранить', 'en' => 'Failed to save settings'],

            // ─── Audit Logs ───────────────────────────────────────────────────
            ['key' => 'audit.date_from', 'group' => 'audit', 'az' => 'Tarixdən', 'ru' => 'От даты', 'en' => 'Date from'],
            ['key' => 'audit.date_to', 'group' => 'audit', 'az' => 'Tarixə', 'ru' => 'До даты', 'en' => 'Date to'],
            ['key' => 'audit.no_logs', 'group' => 'audit', 'az' => 'Jurnal qeydi tapılmadı', 'ru' => 'Записей журнала не найдено', 'en' => 'No audit log entries found'],
            ['key' => 'audit.search_placeholder', 'group' => 'audit', 'az' => 'Təsvir axtar...', 'ru' => 'Поиск по описанию...', 'en' => 'Search logs...'],

            // ─── Strings management ───────────────────────────────────────────
            ['key' => 'strings.key', 'group' => 'strings', 'az' => 'Açar', 'ru' => 'Ключ', 'en' => 'Key'],
            ['key' => 'strings.group', 'group' => 'strings', 'az' => 'Qrup', 'ru' => 'Группа', 'en' => 'Group'],
            ['key' => 'strings.value_az', 'group' => 'strings', 'az' => 'AZ dəyər', 'ru' => 'Значение AZ', 'en' => 'AZ value'],
            ['key' => 'strings.value_ru', 'group' => 'strings', 'az' => 'RU dəyər', 'ru' => 'Значение RU', 'en' => 'RU value'],
            ['key' => 'strings.value_en', 'group' => 'strings', 'az' => 'EN dəyər', 'ru' => 'Значение EN', 'en' => 'EN value'],
            ['key' => 'strings.new', 'group' => 'strings', 'az' => 'Yeni mətn', 'ru' => 'Новая строка', 'en' => 'New String'],
            ['key' => 'strings.created', 'group' => 'strings', 'az' => 'Mətn yaradıldı', 'ru' => 'Строка создана', 'en' => 'String created'],
            ['key' => 'strings.updated', 'group' => 'strings', 'az' => 'Mətn yeniləndi', 'ru' => 'Строка обновлена', 'en' => 'String updated'],
            ['key' => 'strings.deleted', 'group' => 'strings', 'az' => 'Mətn silindi', 'ru' => 'Строка удалена', 'en' => 'String deleted'],

            // ─── History ──────────────────────────────────────────────────────
            ['key' => 'history.title', 'group' => 'history', 'az' => 'Oyun tarixçəsi', 'ru' => 'История игр', 'en' => 'Game History'],
            ['key' => 'history.desc', 'group' => 'history', 'az' => 'Bütün oyun sessiyalarınız', 'ru' => 'Все ваши игровые сессии', 'en' => 'All your game sessions'],
            ['key' => 'history.all_modes', 'group' => 'history', 'az' => 'Bütün rejimlər', 'ru' => 'Все режимы', 'en' => 'All modes'],
            ['key' => 'history.empty', 'group' => 'history', 'az' => 'Hələ oyun oynamamısınız', 'ru' => 'Вы ещё не играли', 'en' => 'No sessions yet. Play your first game!'],
            ['key' => 'history.duration', 'group' => 'history', 'az' => 'Müddət', 'ru' => 'Длительность', 'en' => 'Duration'],
            ['key' => 'history.mode', 'group' => 'history', 'az' => 'Rejim', 'ru' => 'Режим', 'en' => 'Mode'],

            // ─── Errors ───────────────────────────────────────────────────────
            ['key' => 'errors.forbidden', 'group' => 'errors', 'az' => 'Giriş qadağandır', 'ru' => 'Доступ запрещён', 'en' => 'Access forbidden'],
            ['key' => 'errors.not_found', 'group' => 'errors', 'az' => 'Tapılmadı', 'ru' => 'Не найдено', 'en' => 'Not found'],
            ['key' => 'errors.rate_limit', 'group' => 'errors', 'az' => 'Çox tez sorğu', 'ru' => 'Слишком много запросов', 'en' => 'Too many requests'],
            ['key' => 'errors.server_error', 'group' => 'errors', 'az' => 'Server xətası', 'ru' => 'Ошибка сервера', 'en' => 'Server error'],
            ['key' => 'errors.session_expired', 'group' => 'errors', 'az' => 'Sessiya başa çatıb', 'ru' => 'Сессия истекла', 'en' => 'Session expired'],
            ['key' => 'errors.network_error', 'group' => 'errors', 'az' => 'Şəbəkə xətası', 'ru' => 'Ошибка сети', 'en' => 'Network error'],

            // ─── Validation ───────────────────────────────────────────────────
            ['key' => 'validation.required', 'group' => 'validation', 'az' => 'Bu sahə mütləqdir', 'ru' => 'Это поле обязательно', 'en' => 'This field is required'],
            ['key' => 'validation.email_invalid', 'group' => 'validation', 'az' => 'Yanlış email', 'ru' => 'Неверный email', 'en' => 'Invalid email'],
            ['key' => 'validation.password_min', 'group' => 'validation', 'az' => 'Şifrə ən az 8 simvol olmalıdır', 'ru' => 'Пароль должен содержать не менее 8 символов', 'en' => 'Password must be at least 8 characters'],
            ['key' => 'validation.password_mismatch', 'group' => 'validation', 'az' => 'Şifrələr uyğun gəlmir', 'ru' => 'Пароли не совпадают', 'en' => 'Passwords do not match'],
            ['key' => 'validation.username_format', 'group' => 'validation', 'az' => 'Yalnız hərflər, rəqəmlər və _ işarəsi', 'ru' => 'Только буквы, цифры и _', 'en' => 'Only letters, numbers and _'],
            ['key' => 'validation.min_length', 'group' => 'validation', 'az' => 'Ən az :min simvol', 'ru' => 'Минимум :min символов', 'en' => 'At least :min characters'],
            ['key' => 'validation.max_length', 'group' => 'validation', 'az' => 'Ən çox :max simvol', 'ru' => 'Максимум :max символов', 'en' => 'At most :max characters'],

            // ─── Achievement notifications ─────────────────────────────────────
            ['key' => 'achievement.earned', 'group' => 'achievements', 'az' => 'Nailiyyət qazandınız!', 'ru' => 'Достижение получено!', 'en' => 'Achievement earned!'],
            ['key' => 'achievement.xp_earned', 'group' => 'achievements', 'az' => '+:xp XP qazandınız', 'ru' => '+:xp XP получено', 'en' => '+:xp XP earned'],
            ['key' => 'achievements.earned_label', 'group' => 'achievements', 'az' => 'Qazanılmış', 'ru' => 'Получено', 'en' => 'Earned'],
            ['key' => 'achievements.locked_label', 'group' => 'achievements', 'az' => 'Kilidli', 'ru' => 'Заблокировано', 'en' => 'Locked'],
            ['key' => 'achievements.empty', 'group' => 'achievements', 'az' => 'Hələ nailiyyət yoxdur', 'ru' => 'Достижений пока нет', 'en' => 'No achievements yet. Start playing!'],
        ];

        foreach ($strings as $string) {
            SystemString::updateOrCreate(
                ['string_key' => $string['key']],
                [
                    'group_name' => $string['group'],
                    'az' => $string['az'],
                    'ru' => $string['ru'],
                    'en' => $string['en'],
                ]
            );
        }

        $this->command->info('System strings seeded: ' . count($strings) . ' entries.');
    }
}
