<?php

namespace Database\Seeders;

use App\Models\SystemString;
use Illuminate\Database\Seeder;

class SystemStringSeeder extends Seeder
{
    public function run(): void
    {
        $strings = [
            // ─── Auth ─────────────────────────────────────────────────────────
            ['key' => 'auth.login', 'group' => 'auth', 'az' => 'Daxil ol', 'ru' => 'Войти', 'en' => 'Login'],
            ['key' => 'auth.logout', 'group' => 'auth', 'az' => 'Çıxış', 'ru' => 'Выйти', 'en' => 'Logout'],
            ['key' => 'auth.register', 'group' => 'auth', 'az' => 'Qeydiyyat', 'ru' => 'Регистрация', 'en' => 'Register'],
            ['key' => 'auth.login_success', 'group' => 'auth', 'az' => 'Uğurla daxil oldunuz', 'ru' => 'Вход выполнен успешно', 'en' => 'Logged in successfully'],
            ['key' => 'auth.login_failed', 'group' => 'auth', 'az' => 'Giriş məlumatları yanlışdır', 'ru' => 'Неверные данные для входа', 'en' => 'Invalid credentials'],
            ['key' => 'auth.register_success', 'group' => 'auth', 'az' => 'Uğurla qeydiyyatdan keçdiniz', 'ru' => 'Регистрация прошла успешно', 'en' => 'Registered successfully'],
            ['key' => 'auth.register_failed', 'group' => 'auth', 'az' => 'Qeydiyyat uğursuz oldu', 'ru' => 'Регистрация не удалась', 'en' => 'Registration failed'],
            ['key' => 'auth.logout_success', 'group' => 'auth', 'az' => 'Uğurla çıxış etdiniz', 'ru' => 'Вы вышли из системы', 'en' => 'Logged out successfully'],
            ['key' => 'auth.forgot_password', 'group' => 'auth', 'az' => 'Şifrəni unutdum', 'ru' => 'Забыли пароль', 'en' => 'Forgot password'],
            ['key' => 'auth.reset_password', 'group' => 'auth', 'az' => 'Şifrəni yenilə', 'ru' => 'Сбросить пароль', 'en' => 'Reset password'],
            ['key' => 'auth.email', 'group' => 'auth', 'az' => 'Email', 'ru' => 'Электронная почта', 'en' => 'Email'],
            ['key' => 'auth.username', 'group' => 'auth', 'az' => 'İstifadəçi adı', 'ru' => 'Имя пользователя', 'en' => 'Username'],
            ['key' => 'auth.password', 'group' => 'auth', 'az' => 'Şifrə', 'ru' => 'Пароль', 'en' => 'Password'],
            ['key' => 'auth.remember_me', 'group' => 'auth', 'az' => 'Məni xatırla', 'ru' => 'Запомни меня', 'en' => 'Remember me'],
            ['key' => 'auth.no_account', 'group' => 'auth', 'az' => 'Hesabınız yoxdur?', 'ru' => 'Нет аккаунта?', 'en' => 'No account?'],
            ['key' => 'auth.have_account', 'group' => 'auth', 'az' => 'Hesabınız var?', 'ru' => 'Уже есть аккаунт?', 'en' => 'Already have an account?'],
            ['key' => 'auth.forgot_password_desc', 'group' => 'auth', 'az' => 'Email ünvanınızı daxil edin, şifrə sıfırlama linki göndərəcəyik', 'ru' => 'Введите email, мы отправим ссылку для сброса пароля', 'en' => 'Enter your email and we will send a password reset link'],
            ['key' => 'auth.reset_link_sent', 'group' => 'auth', 'az' => 'Sıfırlama linki göndərildi', 'ru' => 'Ссылка для сброса отправлена', 'en' => 'Reset link sent'],
            ['key' => 'auth.reset_link_sent_desc', 'group' => 'auth', 'az' => 'Email ünvanınızı yoxlayın', 'ru' => 'Проверьте вашу почту', 'en' => 'Check your inbox'],
            ['key' => 'auth.send_reset_link', 'group' => 'auth', 'az' => 'Sıfırlama linki göndər', 'ru' => 'Отправить ссылку', 'en' => 'Send reset link'],
            ['key' => 'auth.new_password', 'group' => 'auth', 'az' => 'Yeni şifrə', 'ru' => 'Новый пароль', 'en' => 'New password'],
            ['key' => 'auth.confirm_password', 'group' => 'auth', 'az' => 'Şifrəni təsdiqlə', 'ru' => 'Подтвердите пароль', 'en' => 'Confirm password'],
            ['key' => 'auth.password_reset_success', 'group' => 'auth', 'az' => 'Şifrə uğurla yeniləndi', 'ru' => 'Пароль успешно сброшен', 'en' => 'Password reset successfully'],
            ['key' => 'auth.verifying_email', 'group' => 'auth', 'az' => 'Email doğrulanır...', 'ru' => 'Проверка email...', 'en' => 'Verifying your email address...'],
            ['key' => 'auth.email_verified', 'group' => 'auth', 'az' => 'Email doğrulandı!', 'ru' => 'Email подтверждён!', 'en' => 'Email Verified!'],
            ['key' => 'auth.email_verified_desc', 'group' => 'auth', 'az' => 'Hesabınız uğurla doğrulandı', 'ru' => 'Ваш аккаунт успешно подтверждён', 'en' => 'Your account has been successfully verified'],
            ['key' => 'auth.verification_sent', 'group' => 'auth', 'az' => 'Doğrulama emaili göndərildi', 'ru' => 'Письмо с подтверждением отправлено', 'en' => 'Verification Email Sent'],
            ['key' => 'auth.check_inbox', 'group' => 'auth', 'az' => 'Gelen qutunuzu yoxlayın', 'ru' => 'Проверьте входящие', 'en' => 'Check your inbox and click the link to verify your account'],
            ['key' => 'auth.verification_failed', 'group' => 'auth', 'az' => 'Doğrulama uğursuz oldu', 'ru' => 'Подтверждение не удалось', 'en' => 'Verification Failed'],
            ['key' => 'auth.verification_failed_desc', 'group' => 'auth', 'az' => 'Doğrulama linki etibarsız və ya müddəti bitib', 'ru' => 'Ссылка недействительна или устарела', 'en' => 'The verification link is invalid or has expired'],
            ['key' => 'auth.resend_verification', 'group' => 'auth', 'az' => 'Doğrulama emailini yenidən göndər', 'ru' => 'Повторно отправить письмо', 'en' => 'Resend Verification Email'],
            ['key' => 'auth.back_to_login', 'group' => 'auth', 'az' => 'Girişə qayıt', 'ru' => 'Назад ко входу', 'en' => 'Back to Login'],
            ['key' => 'auth.go_to_dashboard', 'group' => 'auth', 'az' => 'İdarə panelinə keç', 'ru' => 'Перейти на панель', 'en' => 'Go to Dashboard'],
            ['key' => 'auth.first_name', 'group' => 'auth', 'az' => 'Ad', 'ru' => 'Имя', 'en' => 'First name'],
            ['key' => 'auth.last_name', 'group' => 'auth', 'az' => 'Soyad', 'ru' => 'Фамилия', 'en' => 'Last name'],
            ['key' => 'auth.phone', 'group' => 'auth', 'az' => 'Telefon', 'ru' => 'Телефон', 'en' => 'Phone'],
            ['key' => 'auth.school', 'group' => 'auth', 'az' => 'Məktəb', 'ru' => 'Школа', 'en' => 'School'],
            ['key' => 'auth.select_school', 'group' => 'auth', 'az' => 'Məktəb seçin', 'ru' => 'Выберите школу', 'en' => 'Select school'],
            ['key' => 'auth.register_as_teacher', 'group' => 'auth', 'az' => 'Müəllim kimi qeydiyyat', 'ru' => 'Регистрация как учитель', 'en' => 'Register as Teacher'],
            ['key' => 'auth.register_as_parent', 'group' => 'auth', 'az' => 'Valideyn kimi qeydiyyat', 'ru' => 'Регистрация как родитель', 'en' => 'Register as Parent'],
            ['key' => 'auth.child_username', 'group' => 'auth', 'az' => 'Uşağın istifadəçi adı', 'ru' => 'Имя пользователя ребёнка', 'en' => 'Child username'],

            // ─── Common ───────────────────────────────────────────────────────
            ['key' => 'common.save', 'group' => 'common', 'az' => 'Saxla', 'ru' => 'Сохранить', 'en' => 'Save'],
            ['key' => 'common.cancel', 'group' => 'common', 'az' => 'Ləğv et', 'ru' => 'Отмена', 'en' => 'Cancel'],
            ['key' => 'common.delete', 'group' => 'common', 'az' => 'Sil', 'ru' => 'Удалить', 'en' => 'Delete'],
            ['key' => 'common.edit', 'group' => 'common', 'az' => 'Redaktə et', 'ru' => 'Редактировать', 'en' => 'Edit'],
            ['key' => 'common.create', 'group' => 'common', 'az' => 'Yarat', 'ru' => 'Создать', 'en' => 'Create'],
            ['key' => 'common.update', 'group' => 'common', 'az' => 'Yenilə', 'ru' => 'Обновить', 'en' => 'Update'],
            ['key' => 'common.add', 'group' => 'common', 'az' => 'Əlavə et', 'ru' => 'Добавить', 'en' => 'Add'],
            ['key' => 'common.remove', 'group' => 'common', 'az' => 'Çıxar', 'ru' => 'Удалить', 'en' => 'Remove'],
            ['key' => 'common.search', 'group' => 'common', 'az' => 'Axtar', 'ru' => 'Поиск', 'en' => 'Search'],
            ['key' => 'common.filter', 'group' => 'common', 'az' => 'Filtr', 'ru' => 'Фильтр', 'en' => 'Filter'],
            ['key' => 'common.export', 'group' => 'common', 'az' => 'İxrac et', 'ru' => 'Экспорт', 'en' => 'Export'],
            ['key' => 'common.import', 'group' => 'common', 'az' => 'İdxal et', 'ru' => 'Импорт', 'en' => 'Import'],
            ['key' => 'common.loading', 'group' => 'common', 'az' => 'Yüklənir...', 'ru' => 'Загрузка...', 'en' => 'Loading...'],
            ['key' => 'common.no_data', 'group' => 'common', 'az' => 'Məlumat yoxdur', 'ru' => 'Нет данных', 'en' => 'No data'],
            ['key' => 'common.confirm_delete', 'group' => 'common', 'az' => 'Silməyə əminsinizmi?', 'ru' => 'Вы уверены?', 'en' => 'Are you sure you want to delete?'],
            ['key' => 'common.success', 'group' => 'common', 'az' => 'Uğurlu', 'ru' => 'Успешно', 'en' => 'Success'],
            ['key' => 'common.error', 'group' => 'common', 'az' => 'Xəta', 'ru' => 'Ошибка', 'en' => 'Error'],
            ['key' => 'common.all', 'group' => 'common', 'az' => 'Hamısı', 'ru' => 'Все', 'en' => 'All'],
            ['key' => 'common.back', 'group' => 'common', 'az' => 'Geri', 'ru' => 'Назад', 'en' => 'Back'],
            ['key' => 'common.go_back', 'group' => 'common', 'az' => 'Geri qayıt', 'ru' => 'Назад', 'en' => 'Go Back'],
            ['key' => 'common.hide', 'group' => 'common', 'az' => 'Gizlət', 'ru' => 'Скрыть', 'en' => 'Hide'],
            ['key' => 'common.show', 'group' => 'common', 'az' => 'Göstər', 'ru' => 'Показать', 'en' => 'Show'],
            ['key' => 'common.active', 'group' => 'common', 'az' => 'Aktiv', 'ru' => 'Активный', 'en' => 'Active'],
            ['key' => 'common.inactive', 'group' => 'common', 'az' => 'Aktiv deyil', 'ru' => 'Неактивный', 'en' => 'Inactive'],
            ['key' => 'common.enabled', 'group' => 'common', 'az' => 'Aktiv', 'ru' => 'Включено', 'en' => 'Enabled'],
            ['key' => 'common.disabled', 'group' => 'common', 'az' => 'Deaktiv', 'ru' => 'Отключено', 'en' => 'Disabled'],
            ['key' => 'common.optional', 'group' => 'common', 'az' => 'İstəyə bağlı', 'ru' => 'Необязательно', 'en' => 'Optional'],
            ['key' => 'common.required', 'group' => 'common', 'az' => 'Məcburi', 'ru' => 'Обязательно', 'en' => 'Required'],
            ['key' => 'common.language', 'group' => 'common', 'az' => 'Dil', 'ru' => 'Язык', 'en' => 'Language'],
            ['key' => 'common.description', 'group' => 'common', 'az' => 'Təsvir', 'ru' => 'Описание', 'en' => 'Description'],
            ['key' => 'common.name', 'group' => 'common', 'az' => 'Ad', 'ru' => 'Название', 'en' => 'Name'],
            ['key' => 'common.status', 'group' => 'common', 'az' => 'Status', 'ru' => 'Статус', 'en' => 'Status'],
            ['key' => 'common.actions', 'group' => 'common', 'az' => 'Əməliyyatlar', 'ru' => 'Действия', 'en' => 'Actions'],
            ['key' => 'common.close', 'group' => 'common', 'az' => 'Bağla', 'ru' => 'Закрыть', 'en' => 'Close'],
            ['key' => 'common.confirm', 'group' => 'common', 'az' => 'Təsdiqlə', 'ru' => 'Подтвердить', 'en' => 'Confirm'],
            ['key' => 'common.select', 'group' => 'common', 'az' => 'Seçin', 'ru' => 'Выберите', 'en' => 'Select'],
            ['key' => 'common.today', 'group' => 'common', 'az' => 'Bu gün', 'ru' => 'Сегодня', 'en' => 'Today'],
            ['key' => 'common.this_week', 'group' => 'common', 'az' => 'Bu həftə', 'ru' => 'Эта неделя', 'en' => 'week'],
            ['key' => 'common.this_month', 'group' => 'common', 'az' => 'Bu ay', 'ru' => 'Этот месяц', 'en' => 'month'],
            ['key' => 'common.this_year', 'group' => 'common', 'az' => 'Bu il', 'ru' => 'Этот год', 'en' => 'year'],
            ['key' => 'common.from', 'group' => 'common', 'az' => 'Başlanğıc', 'ru' => 'От', 'en' => 'From'],
            ['key' => 'common.to', 'group' => 'common', 'az' => 'Son', 'ru' => 'До', 'en' => 'To'],
            ['key' => 'common.submit', 'group' => 'common', 'az' => 'Göndər', 'ru' => 'Отправить', 'en' => 'Submit'],
            ['key' => 'common.saving', 'group' => 'common', 'az' => 'Saxlanılır...', 'ru' => 'Сохранение...', 'en' => 'Saving...'],
            ['key' => 'common.deleting', 'group' => 'common', 'az' => 'Silinir...', 'ru' => 'Удаление...', 'en' => 'Deleting...'],
            ['key' => 'common.role', 'group' => 'common', 'az' => 'Rol', 'ru' => 'Роль', 'en' => 'Role'],
            ['key' => 'common.permissions', 'group' => 'common', 'az' => 'İcazələr', 'ru' => 'Разрешения', 'en' => 'Permissions'],
            ['key' => 'common.never', 'group' => 'common', 'az' => 'Heç vaxt', 'ru' => 'Никогда', 'en' => 'Never'],

            // ─── Navigation ───────────────────────────────────────────────────
            ['key' => 'nav.dashboard', 'group' => 'navigation', 'az' => 'İdarə paneli', 'ru' => 'Панель управления', 'en' => 'Dashboard'],
            ['key' => 'nav.play', 'group' => 'navigation', 'az' => 'Oyna', 'ru' => 'Играть', 'en' => 'Play'],
            ['key' => 'nav.students', 'group' => 'navigation', 'az' => 'Şagirdlər', 'ru' => 'Ученики', 'en' => 'Students'],
            ['key' => 'nav.teachers', 'group' => 'navigation', 'az' => 'Müəllimlər', 'ru' => 'Учителя', 'en' => 'Teachers'],
            ['key' => 'nav.analytics', 'group' => 'navigation', 'az' => 'Analitika', 'ru' => 'Аналитика', 'en' => 'Analytics'],
            ['key' => 'nav.settings', 'group' => 'navigation', 'az' => 'Parametrlər', 'ru' => 'Настройки', 'en' => 'Settings'],
            ['key' => 'nav.achievements', 'group' => 'navigation', 'az' => 'Nailiyyətlər', 'ru' => 'Достижения', 'en' => 'Achievements'],
            ['key' => 'nav.leaderboard', 'group' => 'navigation', 'az' => 'Liderlik cədvəli', 'ru' => 'Таблица лидеров', 'en' => 'Leaderboard'],
            ['key' => 'nav.history', 'group' => 'navigation', 'az' => 'Tarixçə', 'ru' => 'История', 'en' => 'History'],
            ['key' => 'nav.competitions', 'group' => 'navigation', 'az' => 'Yarışmalar', 'ru' => 'Соревнования', 'en' => 'Competitions'],
            ['key' => 'nav.profile', 'group' => 'navigation', 'az' => 'Profil', 'ru' => 'Профиль', 'en' => 'Profile'],
            ['key' => 'nav.users', 'group' => 'navigation', 'az' => 'İstifadəçilər', 'ru' => 'Пользователи', 'en' => 'Users'],
            ['key' => 'nav.schools', 'group' => 'navigation', 'az' => 'Məktəblər', 'ru' => 'Школы', 'en' => 'Schools'],
            ['key' => 'nav.strings', 'group' => 'navigation', 'az' => 'Sistem mətnləri', 'ru' => 'Системные тексты', 'en' => 'System Strings'],
            ['key' => 'nav.roles', 'group' => 'navigation', 'az' => 'Rollar', 'ru' => 'Роли', 'en' => 'Roles'],
            ['key' => 'nav.texts', 'group' => 'navigation', 'az' => 'Mətnlər', 'ru' => 'Тексты', 'en' => 'Texts'],
            ['key' => 'nav.words', 'group' => 'navigation', 'az' => 'Söz siyahıları', 'ru' => 'Списки слов', 'en' => 'Word Lists'],
            ['key' => 'nav.audit_logs', 'group' => 'navigation', 'az' => 'Audit jurnalı', 'ru' => 'Журнал аудита', 'en' => 'Audit Logs'],
            ['key' => 'nav.children', 'group' => 'navigation', 'az' => 'Uşaqlarım', 'ru' => 'Мои дети', 'en' => 'My Children'],

            // ─── Game ─────────────────────────────────────────────────────────
            ['key' => 'game.start', 'group' => 'game', 'az' => 'Başla', 'ru' => 'Начать', 'en' => 'Start'],
            ['key' => 'game.finish', 'group' => 'game', 'az' => 'Bitir', 'ru' => 'Завершить', 'en' => 'Finish'],
            ['key' => 'game.pause', 'group' => 'game', 'az' => 'Dayandır', 'ru' => 'Пауза', 'en' => 'Pause'],
            ['key' => 'game.wpm', 'group' => 'game', 'az' => 'Söz/dəq', 'ru' => 'Слов/мин', 'en' => 'WPM'],
            ['key' => 'game.select_mode', 'group' => 'game', 'az' => 'Rejimi seçin', 'ru' => 'Выберите режим', 'en' => 'Select mode'],
            ['key' => 'game.select_duration', 'group' => 'game', 'az' => 'Müddəti seçin', 'ru' => 'Выберите длительность', 'en' => 'Select duration'],
            ['key' => 'game.random_words', 'group' => 'game', 'az' => 'Təsadüfi sözlər', 'ru' => 'Случайные слова', 'en' => 'Random words'],
            ['key' => 'game.text_reading', 'group' => 'game', 'az' => 'Mətn oxuma', 'ru' => 'Чтение текста', 'en' => 'Text reading'],
            ['key' => 'game.sentence_reading', 'group' => 'game', 'az' => 'Cümlə oxuma', 'ru' => 'Чтение предложений', 'en' => 'Sentence reading'],
            ['key' => 'game.memory', 'group' => 'game', 'az' => 'Yaddaş', 'ru' => 'Память', 'en' => 'Memory'],
            ['key' => 'game.ai_mode', 'group' => 'game', 'az' => 'AI rejimi', 'ru' => 'Режим ИИ', 'en' => 'AI mode'],
            ['key' => 'game.finished', 'group' => 'game', 'az' => 'Oyun bitdi! :wpm söz/dəqiqə', 'ru' => 'Игра завершена! :wpm слов/мин', 'en' => 'Game finished! :wpm WPM'],
            ['key' => 'game.start_failed', 'group' => 'game', 'az' => 'Oyun başladıla bilmədi', 'ru' => 'Не удалось начать игру', 'en' => 'Failed to start game'],
            ['key' => 'game.click_words', 'group' => 'game', 'az' => 'Sözlərə sırayla klikləyin', 'ru' => 'Нажимайте слова по порядку', 'en' => 'Click words in order'],
            ['key' => 'game.countdown', 'group' => 'game', 'az' => 'Hazır olun...', 'ru' => 'Приготовьтесь...', 'en' => 'Get ready...'],
            ['key' => 'game.results', 'group' => 'game', 'az' => 'Nəticə', 'ru' => 'Результат', 'en' => 'Results'],
            ['key' => 'game.play_again', 'group' => 'game', 'az' => 'Yenidən oyna', 'ru' => 'Играть снова', 'en' => 'Play again'],
            ['key' => 'game.accuracy', 'group' => 'game', 'az' => 'Dəqiqlik', 'ru' => 'Точность', 'en' => 'Accuracy'],
            ['key' => 'game.words_read', 'group' => 'game', 'az' => 'Oxunan sözlər', 'ru' => 'Прочитано слов', 'en' => 'Words read'],
            ['key' => 'game.time', 'group' => 'game', 'az' => 'Vaxt', 'ru' => 'Время', 'en' => 'Time'],
            ['key' => 'game.xp_earned', 'group' => 'game', 'az' => '+:xp XP qazandınız', 'ru' => '+:xp XP получено', 'en' => '+:xp XP earned'],
            ['key' => 'game.select_language', 'group' => 'game', 'az' => 'Dil seçin', 'ru' => 'Выберите язык', 'en' => 'Select language'],
            ['key' => 'game.select_difficulty', 'group' => 'game', 'az' => 'Çətinlik seçin', 'ru' => 'Выберите сложность', 'en' => 'Select difficulty'],

            // ─── Analytics ────────────────────────────────────────────────────
            ['key' => 'analytics.no_data', 'group' => 'analytics', 'az' => 'Məlumat yoxdur', 'ru' => 'Нет данных', 'en' => 'No data available'],
            ['key' => 'analytics.sessions', 'group' => 'analytics', 'az' => 'Sessiyalar', 'ru' => 'Сессии', 'en' => 'Sessions'],
            ['key' => 'analytics.wpm', 'group' => 'analytics', 'az' => 'Söz/dəq', 'ru' => 'Слов/мин', 'en' => 'WPM'],
            ['key' => 'analytics.avg_wpm', 'group' => 'analytics', 'az' => 'Ort. söz/dəq', 'ru' => 'Ср. слов/мин', 'en' => 'Avg WPM'],
            ['key' => 'analytics.best_wpm', 'group' => 'analytics', 'az' => 'Ən yaxşı söz/dəq', 'ru' => 'Лучший показатель', 'en' => 'Best WPM'],
            ['key' => 'analytics.wpm_trend', 'group' => 'analytics', 'az' => 'Söz/dəq trendi', 'ru' => 'Тренд слов/мин', 'en' => 'WPM Trend'],
            ['key' => 'analytics.daily_activity', 'group' => 'analytics', 'az' => 'Günlük aktivlik', 'ru' => 'Дневная активность', 'en' => 'Daily Activity'],
            ['key' => 'analytics.by_language', 'group' => 'analytics', 'az' => 'Dilə görə', 'ru' => 'По языку', 'en' => 'By Language'],
            ['key' => 'analytics.by_mode', 'group' => 'analytics', 'az' => 'Rejimə görə', 'ru' => 'По режиму', 'en' => 'By Game Mode'],
            ['key' => 'analytics.today', 'group' => 'analytics', 'az' => 'Bu gün', 'ru' => 'Сегодня', 'en' => 'Today'],
            ['key' => 'analytics.total_sessions', 'group' => 'analytics', 'az' => 'Cəmi sessiyalar', 'ru' => 'Всего сессий', 'en' => 'Total Sessions'],
            ['key' => 'analytics.overview', 'group' => 'analytics', 'az' => 'Ümumi baxış', 'ru' => 'Обзор', 'en' => 'Overview'],
            ['key' => 'analytics.my_stats', 'group' => 'analytics', 'az' => 'Mənim statistikam', 'ru' => 'Моя статистика', 'en' => 'My Stats'],
            ['key' => 'analytics.weakest_words', 'group' => 'analytics', 'az' => 'Ən zəif sözlər', 'ru' => 'Слабые слова', 'en' => 'Weakest Words'],
            ['key' => 'analytics.export', 'group' => 'analytics', 'az' => 'İxrac et', 'ru' => 'Экспорт', 'en' => 'Export'],

            // ─── Gamification ─────────────────────────────────────────────────
            ['key' => 'gamification.level', 'group' => 'gamification', 'az' => 'Səviyyə', 'ru' => 'Уровень', 'en' => 'Level'],
            ['key' => 'gamification.xp', 'group' => 'gamification', 'az' => 'Təcrübə xalı', 'ru' => 'Очки опыта', 'en' => 'XP'],
            ['key' => 'gamification.to_next', 'group' => 'gamification', 'az' => 'növbəti səviyyəyə', 'ru' => 'до следующего', 'en' => 'to next'],
            ['key' => 'gamification.streak', 'group' => 'gamification', 'az' => ':days günlük seriya!', 'ru' => 'Серия :days дней!', 'en' => ':days day streak!'],
            ['key' => 'gamification.achievements', 'group' => 'gamification', 'az' => 'Nailiyyətlər', 'ru' => 'Достижения', 'en' => 'Achievements'],
            ['key' => 'gamification.recent_achievements', 'group' => 'gamification', 'az' => 'Son nailiyyətlər', 'ru' => 'Последние достижения', 'en' => 'Recent Achievements'],
            ['key' => 'gamification.locked', 'group' => 'gamification', 'az' => 'Kilidli', 'ru' => 'Заблокировано', 'en' => 'Locked'],
            ['key' => 'gamification.earned', 'group' => 'gamification', 'az' => 'Qazanıldı', 'ru' => 'Получено', 'en' => 'Earned'],
            ['key' => 'gamification.rank', 'group' => 'gamification', 'az' => 'Sıra', 'ru' => 'Место', 'en' => 'Rank'],
            ['key' => 'gamification.level_up', 'group' => 'gamification', 'az' => 'Səviyyə yüksəldi! Səviyyə :level', 'ru' => 'Уровень повышен! Уровень :level', 'en' => 'Level up! Level :level'],

            // ─── Leaderboard ──────────────────────────────────────────────────
            ['key' => 'leaderboard.global', 'group' => 'leaderboard', 'az' => 'Ümumi', 'ru' => 'Глобальный', 'en' => 'Global'],
            ['key' => 'leaderboard.school', 'group' => 'leaderboard', 'az' => 'Məktəb', 'ru' => 'Школа', 'en' => 'School'],
            ['key' => 'leaderboard.class', 'group' => 'leaderboard', 'az' => 'Sinif', 'ru' => 'Класс', 'en' => 'Class'],
            ['key' => 'leaderboard.by_xp', 'group' => 'leaderboard', 'az' => 'XP-yə görə', 'ru' => 'По XP', 'en' => 'By XP'],
            ['key' => 'leaderboard.by_wpm', 'group' => 'leaderboard', 'az' => 'Sürətə görə', 'ru' => 'По скорости', 'en' => 'By WPM'],
            ['key' => 'leaderboard.by_sessions', 'group' => 'leaderboard', 'az' => 'Sessiyalara görə', 'ru' => 'По сессиям', 'en' => 'By Sessions'],
            ['key' => 'leaderboard.you', 'group' => 'leaderboard', 'az' => 'Siz', 'ru' => 'Вы', 'en' => 'You'],
            ['key' => 'leaderboard.empty', 'group' => 'leaderboard', 'az' => 'Hələ ki liderlik cədvəli yoxdur', 'ru' => 'Таблица лидеров пуста', 'en' => 'No leaderboard entries yet'],

            // ─── Profile ──────────────────────────────────────────────────────
            ['key' => 'profile.title', 'group' => 'profile', 'az' => 'Profil', 'ru' => 'Профиль', 'en' => 'Profile'],
            ['key' => 'profile.avatar', 'group' => 'profile', 'az' => 'Avatar', 'ru' => 'Аватар', 'en' => 'Avatar'],
            ['key' => 'profile.change_avatar', 'group' => 'profile', 'az' => 'Avatarı dəyiş', 'ru' => 'Изменить аватар', 'en' => 'Change avatar'],
            ['key' => 'profile.personal_info', 'group' => 'profile', 'az' => 'Şəxsi məlumatlar', 'ru' => 'Личные данные', 'en' => 'Personal info'],
            ['key' => 'profile.change_password', 'group' => 'profile', 'az' => 'Şifrəni dəyiş', 'ru' => 'Изменить пароль', 'en' => 'Change password'],
            ['key' => 'profile.current_password', 'group' => 'profile', 'az' => 'Cari şifrə', 'ru' => 'Текущий пароль', 'en' => 'Current password'],
            ['key' => 'profile.new_password', 'group' => 'profile', 'az' => 'Yeni şifrə', 'ru' => 'Новый пароль', 'en' => 'New password'],
            ['key' => 'profile.updated', 'group' => 'profile', 'az' => 'Profil yeniləndi', 'ru' => 'Профиль обновлён', 'en' => 'Profile updated'],
            ['key' => 'profile.password_updated', 'group' => 'profile', 'az' => 'Şifrə yeniləndi', 'ru' => 'Пароль обновлён', 'en' => 'Password updated'],
            ['key' => 'profile.avatar_uploaded', 'group' => 'profile', 'az' => 'Avatar yükləndi', 'ru' => 'Аватар загружен', 'en' => 'Avatar uploaded'],
            ['key' => 'profile.preferred_language', 'group' => 'profile', 'az' => 'Üstünlük verilən dil', 'ru' => 'Предпочтительный язык', 'en' => 'Preferred language'],
            ['key' => 'profile.my_stats', 'group' => 'profile', 'az' => 'Mənim statistikam', 'ru' => 'Моя статистика', 'en' => 'My Stats'],

            // ─── Notifications ────────────────────────────────────────────────
            ['key' => 'notifications.title', 'group' => 'notifications', 'az' => 'Bildirişlər', 'ru' => 'Уведомления', 'en' => 'Notifications'],
            ['key' => 'notifications.empty', 'group' => 'notifications', 'az' => 'Bildiriş yoxdur', 'ru' => 'Нет уведомлений', 'en' => 'No notifications'],
            ['key' => 'notifications.mark_all_read', 'group' => 'notifications', 'az' => 'Hamısını oxunmuş et', 'ru' => 'Отметить все прочитанными', 'en' => 'Mark all as read'],
            ['key' => 'notifications.view_all', 'group' => 'notifications', 'az' => 'Hamısına bax', 'ru' => 'Посмотреть все', 'en' => 'View all'],
            ['key' => 'notifications.achievement_earned', 'group' => 'notifications', 'az' => 'Nailiyyət qazandınız: :name', 'ru' => 'Достижение получено: :name', 'en' => 'Achievement earned: :name'],
            ['key' => 'notifications.streak_milestone', 'group' => 'notifications', 'az' => ':days günlük seriya!', 'ru' => 'Серия :days дней!', 'en' => ':days day streak!'],
            ['key' => 'notifications.level_up', 'group' => 'notifications', 'az' => 'Səviyyə :level-ə yüksəldiniz!', 'ru' => 'Вы достигли уровня :level!', 'en' => 'You reached level :level!'],

            // ─── Admin ────────────────────────────────────────────────────────
            ['key' => 'admin.users_desc', 'group' => 'admin', 'az' => 'Platforma istifadəçilərini idarə edin', 'ru' => 'Управление пользователями платформы', 'en' => 'Manage platform users'],
            ['key' => 'admin.strings_desc', 'group' => 'admin', 'az' => 'UI mətnlərini idarə edin', 'ru' => 'Управление текстами интерфейса', 'en' => 'Manage UI strings'],
            ['key' => 'admin.schools_desc', 'group' => 'admin', 'az' => 'Məktəb və sinifləri idarə edin', 'ru' => 'Управление школами и классами', 'en' => 'Manage schools and classes'],
            ['key' => 'admin.roles_desc', 'group' => 'admin', 'az' => 'Rol və icazələri idarə edin', 'ru' => 'Управление ролями и разрешениями', 'en' => 'Manage roles and permissions'],
            ['key' => 'admin.texts_desc', 'group' => 'admin', 'az' => 'Oxuma mətnlərini idarə edin', 'ru' => 'Управление текстами для чтения', 'en' => 'Manage reading texts'],
            ['key' => 'admin.words_desc', 'group' => 'admin', 'az' => 'Məşq söz siyahılarını idarə edin', 'ru' => 'Управление списками слов', 'en' => 'Manage word lists used in reading exercises'],
            ['key' => 'admin.settings_desc', 'group' => 'admin', 'az' => 'Platformanın ümumi parametrləri', 'ru' => 'Общие настройки платформы', 'en' => 'General platform settings'],
            ['key' => 'admin.competitions_desc', 'group' => 'admin', 'az' => 'Yarışmaları idarə edin', 'ru' => 'Управление соревнованиями', 'en' => 'Manage competitions'],
            ['key' => 'admin.audit_logs_desc', 'group' => 'admin', 'az' => 'Sistem fəaliyyətini izləyin', 'ru' => 'Мониторинг активности системы', 'en' => 'Monitor system activity'],
            ['key' => 'admin.analytics_desc', 'group' => 'admin', 'az' => 'Platforma analitikasına baxın', 'ru' => 'Просмотр аналитики платформы', 'en' => 'View platform-wide analytics'],
            ['key' => 'admin.total_users', 'group' => 'admin', 'az' => 'Cəmi istifadəçilər', 'ru' => 'Всего пользователей', 'en' => 'Total Users'],
            ['key' => 'admin.active_users', 'group' => 'admin', 'az' => 'Aktiv istifadəçilər', 'ru' => 'Активные пользователи', 'en' => 'Active Users'],
            ['key' => 'admin.total_sessions', 'group' => 'admin', 'az' => 'Cəmi sessiyalar', 'ru' => 'Всего сессий', 'en' => 'Total Sessions'],
            ['key' => 'admin.total_schools', 'group' => 'admin', 'az' => 'Cəmi məktəblər', 'ru' => 'Всего школ', 'en' => 'Total Schools'],
            ['key' => 'admin.invite_user', 'group' => 'admin', 'az' => 'İstifadəçi dəvət et', 'ru' => 'Пригласить пользователя', 'en' => 'Invite User'],
            ['key' => 'admin.add_school', 'group' => 'admin', 'az' => 'Məktəb əlavə et', 'ru' => 'Добавить школу', 'en' => 'Add School'],
            ['key' => 'admin.manage_roles', 'group' => 'admin', 'az' => 'Rolları idarə et', 'ru' => 'Управление ролями', 'en' => 'Manage Roles'],
            ['key' => 'admin.view_logs', 'group' => 'admin', 'az' => 'Jurnala bax', 'ru' => 'Просмотр журнала', 'en' => 'View Logs'],
            ['key' => 'admin.system_settings', 'group' => 'admin', 'az' => 'Sistem parametrləri', 'ru' => 'Системные настройки', 'en' => 'System Settings'],
            ['key' => 'admin.no_users', 'group' => 'admin', 'az' => 'İstifadəçi tapılmadı', 'ru' => 'Пользователи не найдены', 'en' => 'No users found'],
            ['key' => 'admin.deactivate', 'group' => 'admin', 'az' => 'Deaktiv et', 'ru' => 'Деактивировать', 'en' => 'Deactivate'],
            ['key' => 'admin.activate', 'group' => 'admin', 'az' => 'Aktiv et', 'ru' => 'Активировать', 'en' => 'Activate'],

            // ─── Teacher ──────────────────────────────────────────────────────
            ['key' => 'teacher.students_desc', 'group' => 'teacher', 'az' => 'Sinfinizin şagirdlərini izləyin', 'ru' => 'Отслеживайте учеников вашего класса', 'en' => "Monitor your class's students"],
            ['key' => 'teacher.analytics_desc', 'group' => 'teacher', 'az' => 'Sinfinizin performans icmalı', 'ru' => 'Обзор успеваемости вашего класса', 'en' => "Your class's performance overview"],
            ['key' => 'teacher.total_students', 'group' => 'teacher', 'az' => 'Şagirdlər', 'ru' => 'Ученики', 'en' => 'Students'],
            ['key' => 'teacher.active_today', 'group' => 'teacher', 'az' => 'Bu gün aktiv', 'ru' => 'Активны сегодня', 'en' => 'Active Today'],
            ['key' => 'teacher.top_students', 'group' => 'teacher', 'az' => 'Ən yaxşı şagirdlər', 'ru' => 'Лучшие ученики', 'en' => 'Top Students'],
            ['key' => 'teacher.no_students', 'group' => 'teacher', 'az' => 'Hələ şagird yoxdur', 'ru' => 'Учеников пока нет', 'en' => 'No students yet'],

            // ─── Parent ───────────────────────────────────────────────────────
            ['key' => 'parent.children_desc', 'group' => 'parent', 'az' => 'Uşaqlarınızın inkişafına ətraflı baxış', 'ru' => 'Подробный просмотр прогресса ваших детей', 'en' => "Detailed view of your children's progress"],
            ['key' => 'parent.no_children', 'group' => 'parent', 'az' => 'Hesabınıza bağlı uşaq yoxdur', 'ru' => 'Нет детей, привязанных к вашему аккаунту', 'en' => 'No children linked to your account'],
            ['key' => 'parent.view_progress', 'group' => 'parent', 'az' => 'Tam hesabat', 'ru' => 'Полный отчёт', 'en' => 'Full Report'],
            ['key' => 'parent.child_not_found', 'group' => 'parent', 'az' => 'Uşaq tapılmadı', 'ru' => 'Ребёнок не найден', 'en' => 'Child not found'],

            // ─── Competitions ─────────────────────────────────────────────────
            ['key' => 'competitions.desc', 'group' => 'competitions', 'az' => 'Başqaları ilə yarışın və reytinqdə yuxarı qalxın', 'ru' => 'Соревнуйтесь с другими и поднимайтесь в рейтинге', 'en' => 'Compete with others and climb the rankings'],
            ['key' => 'competitions.active', 'group' => 'competitions', 'az' => 'Aktiv', 'ru' => 'Активные', 'en' => 'Active'],
            ['key' => 'competitions.upcoming', 'group' => 'competitions', 'az' => 'Gələcək', 'ru' => 'Предстоящие', 'en' => 'Upcoming'],
            ['key' => 'competitions.ended', 'group' => 'competitions', 'az' => 'Başa çatıb', 'ru' => 'Завершённые', 'en' => 'Ended'],
            ['key' => 'competitions.none', 'group' => 'competitions', 'az' => 'Hal-hazırda yarışma yoxdur', 'ru' => 'Соревнований пока нет', 'en' => 'No competitions available right now'],
            ['key' => 'competitions.join', 'group' => 'competitions', 'az' => 'Qoşul', 'ru' => 'Присоединиться', 'en' => 'Join'],
            ['key' => 'competitions.joined', 'group' => 'competitions', 'az' => 'Yarışmaya qoşuldunuz!', 'ru' => 'Вы присоединились к соревнованию!', 'en' => 'Joined competition!'],
            ['key' => 'competitions.joined_label', 'group' => 'competitions', 'az' => 'Qoşuldu', 'ru' => 'Присоединился', 'en' => 'Joined'],
            ['key' => 'competitions.join_error', 'group' => 'competitions', 'az' => 'Yarışmaya qoşulmaq mümkün olmadı', 'ru' => 'Не удалось присоединиться', 'en' => 'Could not join competition'],
            ['key' => 'competitions.participants', 'group' => 'competitions', 'az' => 'iştirakçı', 'ru' => 'участников', 'en' => 'participants'],
            ['key' => 'competitions.starts_in', 'group' => 'competitions', 'az' => 'Başlayır', 'ru' => 'Начнётся', 'en' => 'Starts'],
            ['key' => 'competitions.ends_in', 'group' => 'competitions', 'az' => 'Bitir', 'ru' => 'Заканчивается', 'en' => 'Ends'],
            ['key' => 'competitions.ended_ago', 'group' => 'competitions', 'az' => 'Bitdi', 'ru' => 'Завершилось', 'en' => 'Ended'],
            ['key' => 'competitions.no_scores', 'group' => 'competitions', 'az' => 'Hələ nəticə yoxdur', 'ru' => 'Результатов пока нет', 'en' => 'No scores yet'],
            ['key' => 'competitions.view_board', 'group' => 'competitions', 'az' => 'Liderlik', 'ru' => 'Рейтинг', 'en' => 'Leaderboard'],
            ['key' => 'competitions.title', 'group' => 'competitions', 'az' => 'Başlıq', 'ru' => 'Заголовок', 'en' => 'Title'],
            ['key' => 'competitions.starts_at', 'group' => 'competitions', 'az' => 'Başlama vaxtı', 'ru' => 'Дата начала', 'en' => 'Starts at'],
            ['key' => 'competitions.ends_at', 'group' => 'competitions', 'az' => 'Bitmə vaxtı', 'ru' => 'Дата окончания', 'en' => 'Ends at'],
            ['key' => 'competitions.max_participants', 'group' => 'competitions', 'az' => 'Maks. iştirakçı', 'ru' => 'Макс. участников', 'en' => 'Max participants'],
            ['key' => 'competitions.created', 'group' => 'competitions', 'az' => 'Yarışma yaradıldı', 'ru' => 'Соревнование создано', 'en' => 'Competition created'],
            ['key' => 'competitions.deleted', 'group' => 'competitions', 'az' => 'Yarışma silindi', 'ru' => 'Соревнование удалено', 'en' => 'Competition deleted'],
            ['key' => 'competitions.delete_confirm', 'group' => 'competitions', 'az' => 'Bu yarışmanı silmək istəyirsinizmi?', 'ru' => 'Удалить это соревнование?', 'en' => 'Delete this competition?'],
            ['key' => 'competitions.new', 'group' => 'competitions', 'az' => 'Yeni yarışma', 'ru' => 'Новое соревнование', 'en' => 'New Competition'],

            // ─── Texts ────────────────────────────────────────────────────────
            ['key' => 'texts.title', 'group' => 'texts', 'az' => 'Mətnlər', 'ru' => 'Тексты', 'en' => 'Texts'],
            ['key' => 'texts.new', 'group' => 'texts', 'az' => 'Yeni mətn', 'ru' => 'Новый текст', 'en' => 'New Text'],
            ['key' => 'texts.title_label', 'group' => 'texts', 'az' => 'Başlıq', 'ru' => 'Заголовок', 'en' => 'Title'],
            ['key' => 'texts.content', 'group' => 'texts', 'az' => 'Mətn', 'ru' => 'Текст', 'en' => 'Content'],
            ['key' => 'texts.difficulty', 'group' => 'texts', 'az' => 'Çətinlik', 'ru' => 'Сложность', 'en' => 'Difficulty'],
            ['key' => 'texts.beginner', 'group' => 'texts', 'az' => 'Başlanğıc', 'ru' => 'Начинающий', 'en' => 'Beginner'],
            ['key' => 'texts.intermediate', 'group' => 'texts', 'az' => 'Orta', 'ru' => 'Средний', 'en' => 'Intermediate'],
            ['key' => 'texts.advanced', 'group' => 'texts', 'az' => 'İrəliləmiş', 'ru' => 'Продвинутый', 'en' => 'Advanced'],
            ['key' => 'texts.word_count', 'group' => 'texts', 'az' => 'Söz sayı', 'ru' => 'Кол-во слов', 'en' => 'Word count'],
            ['key' => 'texts.created', 'group' => 'texts', 'az' => 'Mətn yaradıldı', 'ru' => 'Текст создан', 'en' => 'Text created'],
            ['key' => 'texts.updated', 'group' => 'texts', 'az' => 'Mətn yeniləndi', 'ru' => 'Текст обновлён', 'en' => 'Text updated'],
            ['key' => 'texts.deleted', 'group' => 'texts', 'az' => 'Mətn silindi', 'ru' => 'Текст удалён', 'en' => 'Text deleted'],
            ['key' => 'texts.delete_confirm', 'group' => 'texts', 'az' => 'Bu mətni silmək istəyirsinizmi?', 'ru' => 'Удалить этот текст?', 'en' => 'Delete this text?'],
            ['key' => 'texts.none', 'group' => 'texts', 'az' => 'Mətn tapılmadı', 'ru' => 'Тексты не найдены', 'en' => 'No texts found'],

            // ─── Words ────────────────────────────────────────────────────────
            ['key' => 'words.new_list', 'group' => 'words', 'az' => 'Yeni söz siyahısı', 'ru' => 'Новый список слов', 'en' => 'New List'],
            ['key' => 'words.list_name', 'group' => 'words', 'az' => 'Siyahı adı', 'ru' => 'Название списка', 'en' => 'List Name'],
            ['key' => 'words.list_name_placeholder', 'group' => 'words', 'az' => 'məs. Başlanğıc Azərbaycan', 'ru' => 'напр. Начинающий Азербайджан', 'en' => 'e.g. Beginner Azerbaijani'],
            ['key' => 'words.difficulty', 'group' => 'words', 'az' => 'Çətinlik', 'ru' => 'Сложность', 'en' => 'Difficulty'],
            ['key' => 'words.beginner', 'group' => 'words', 'az' => 'Başlanğıc', 'ru' => 'Начинающий', 'en' => 'Beginner'],
            ['key' => 'words.intermediate', 'group' => 'words', 'az' => 'Orta', 'ru' => 'Средний', 'en' => 'Intermediate'],
            ['key' => 'words.advanced', 'group' => 'words', 'az' => 'İrəliləmiş', 'ru' => 'Продвинутый', 'en' => 'Advanced'],
            ['key' => 'words.words', 'group' => 'words', 'az' => 'söz', 'ru' => 'слов', 'en' => 'words'],
            ['key' => 'words.manage_words', 'group' => 'words', 'az' => 'Sözlər', 'ru' => 'Слова', 'en' => 'Words'],
            ['key' => 'words.new_word_placeholder', 'group' => 'words', 'az' => 'Söz əlavə et...', 'ru' => 'Добавить слово...', 'en' => 'Add a word...'],
            ['key' => 'words.word_added', 'group' => 'words', 'az' => 'Söz əlavə edildi', 'ru' => 'Слово добавлено', 'en' => 'Word added'],
            ['key' => 'words.no_words', 'group' => 'words', 'az' => 'Hələ söz yoxdur', 'ru' => 'Слов пока нет', 'en' => 'No words yet. Add some above.'],
            ['key' => 'words.list_created', 'group' => 'words', 'az' => 'Söz siyahısı yaradıldı', 'ru' => 'Список слов создан', 'en' => 'Word list created'],
            ['key' => 'words.list_deleted', 'group' => 'words', 'az' => 'Söz siyahısı silindi', 'ru' => 'Список слов удалён', 'en' => 'Word list deleted'],
            ['key' => 'words.delete_list_title', 'group' => 'words', 'az' => 'Söz siyahısını silin?', 'ru' => 'Удалить список слов?', 'en' => 'Delete Word List?'],
            ['key' => 'words.delete_list_desc', 'group' => 'words', 'az' => 'Bu siyahı və bütün sözlər daimi silinəcək', 'ru' => 'Список и все слова будут удалены навсегда', 'en' => 'This will permanently delete the list and all its words'],
            ['key' => 'words.no_lists', 'group' => 'words', 'az' => 'Söz siyahısı tapılmadı', 'ru' => 'Списки слов не найдены', 'en' => 'No word lists found'],

            // ─── Settings ─────────────────────────────────────────────────────
            ['key' => 'settings.maintenance_mode', 'group' => 'settings', 'az' => 'Texniki xidmət rejimi', 'ru' => 'Режим обслуживания', 'en' => 'Maintenance mode'],
            ['key' => 'settings.maintenance_desc', 'group' => 'settings', 'az' => 'Sayt texniki xidmət üçün bağlanacaq', 'ru' => 'Сайт будет закрыт для обслуживания', 'en' => 'Site will be closed for maintenance'],
            ['key' => 'settings.registration_enabled', 'group' => 'settings', 'az' => 'Qeydiyyat açıq', 'ru' => 'Регистрация открыта', 'en' => 'Registration enabled'],
            ['key' => 'settings.registration_desc', 'group' => 'settings', 'az' => 'Yeni istifadəçilərin qeydiyyatına icazə ver', 'ru' => 'Разрешить регистрацию новых пользователей', 'en' => 'Allow new user registrations'],
            ['key' => 'settings.game_modes', 'group' => 'settings', 'az' => 'Oyun rejimləri', 'ru' => 'Игровые режимы', 'en' => 'Game modes'],
            ['key' => 'settings.game_modes_desc', 'group' => 'settings', 'az' => 'Aktiv oyun rejimlərini seçin', 'ru' => 'Выберите активные игровые режимы', 'en' => 'Select active game modes'],
            ['key' => 'settings.token_expiry', 'group' => 'settings', 'az' => 'Token müddəti (dəqiqə)', 'ru' => 'Срок действия токена (мин)', 'en' => 'Token expiry (minutes)'],
            ['key' => 'settings.saved', 'group' => 'settings', 'az' => 'Parametrlər yadda saxlanıldı', 'ru' => 'Настройки сохранены', 'en' => 'Settings saved'],
            ['key' => 'settings.save_error', 'group' => 'settings', 'az' => 'Yadda saxlamaq uğursuz oldu', 'ru' => 'Не удалось сохранить', 'en' => 'Failed to save settings'],

            // ─── Audit Logs ───────────────────────────────────────────────────
            ['key' => 'audit.date_from', 'group' => 'audit', 'az' => 'Tarixdən', 'ru' => 'От даты', 'en' => 'Date from'],
            ['key' => 'audit.date_to', 'group' => 'audit', 'az' => 'Tarixə', 'ru' => 'До даты', 'en' => 'Date to'],
            ['key' => 'audit.no_logs', 'group' => 'audit', 'az' => 'Jurnal qeydi tapılmadı', 'ru' => 'Записей журнала не найдено', 'en' => 'No audit log entries found'],
            ['key' => 'audit.search_placeholder', 'group' => 'audit', 'az' => 'Təsvir axtar...', 'ru' => 'Поиск по описанию...', 'en' => 'Search logs...'],

            // ─── Strings management ───────────────────────────────────────────
            ['key' => 'strings.key', 'group' => 'strings', 'az' => 'Açar', 'ru' => 'Ключ', 'en' => 'Key'],
            ['key' => 'strings.group', 'group' => 'strings', 'az' => 'Qrup', 'ru' => 'Группа', 'en' => 'Group'],
            ['key' => 'strings.value_az', 'group' => 'strings', 'az' => 'AZ dəyər', 'ru' => 'Значение AZ', 'en' => 'AZ value'],
            ['key' => 'strings.value_ru', 'group' => 'strings', 'az' => 'RU dəyər', 'ru' => 'Значение RU', 'en' => 'RU value'],
            ['key' => 'strings.value_en', 'group' => 'strings', 'az' => 'EN dəyər', 'ru' => 'Значение EN', 'en' => 'EN value'],
            ['key' => 'strings.new', 'group' => 'strings', 'az' => 'Yeni mətn', 'ru' => 'Новая строка', 'en' => 'New String'],
            ['key' => 'strings.created', 'group' => 'strings', 'az' => 'Mətn yaradıldı', 'ru' => 'Строка создана', 'en' => 'String created'],
            ['key' => 'strings.updated', 'group' => 'strings', 'az' => 'Mətn yeniləndi', 'ru' => 'Строка обновлена', 'en' => 'String updated'],
            ['key' => 'strings.deleted', 'group' => 'strings', 'az' => 'Mətn silindi', 'ru' => 'Строка удалена', 'en' => 'String deleted'],

            // ─── History ──────────────────────────────────────────────────────
            ['key' => 'history.title', 'group' => 'history', 'az' => 'Oyun tarixçəsi', 'ru' => 'История игр', 'en' => 'Game History'],
            ['key' => 'history.desc', 'group' => 'history', 'az' => 'Bütün oyun sessiyalarınız', 'ru' => 'Все ваши игровые сессии', 'en' => 'All your game sessions'],
            ['key' => 'history.all_modes', 'group' => 'history', 'az' => 'Bütün rejimlər', 'ru' => 'Все режимы', 'en' => 'All modes'],
            ['key' => 'history.empty', 'group' => 'history', 'az' => 'Hələ oyun oynamamısınız', 'ru' => 'Вы ещё не играли', 'en' => 'No sessions yet. Play your first game!'],
            ['key' => 'history.duration', 'group' => 'history', 'az' => 'Müddət', 'ru' => 'Длительность', 'en' => 'Duration'],
            ['key' => 'history.mode', 'group' => 'history', 'az' => 'Rejim', 'ru' => 'Режим', 'en' => 'Mode'],

            // ─── Errors ───────────────────────────────────────────────────────
            ['key' => 'errors.forbidden', 'group' => 'errors', 'az' => 'Giriş qadağandır', 'ru' => 'Доступ запрещён', 'en' => 'Access forbidden'],
            ['key' => 'errors.not_found', 'group' => 'errors', 'az' => 'Tapılmadı', 'ru' => 'Не найдено', 'en' => 'Not found'],
            ['key' => 'errors.rate_limit', 'group' => 'errors', 'az' => 'Çox tez sorğu', 'ru' => 'Слишком много запросов', 'en' => 'Too many requests'],
            ['key' => 'errors.server_error', 'group' => 'errors', 'az' => 'Server xətası', 'ru' => 'Ошибка сервера', 'en' => 'Server error'],
            ['key' => 'errors.session_expired', 'group' => 'errors', 'az' => 'Sessiya başa çatıb', 'ru' => 'Сессия истекла', 'en' => 'Session expired'],
            ['key' => 'errors.network_error', 'group' => 'errors', 'az' => 'Şəbəkə xətası', 'ru' => 'Ошибка сети', 'en' => 'Network error'],

            // ─── Validation ───────────────────────────────────────────────────
            ['key' => 'validation.required', 'group' => 'validation', 'az' => 'Bu sahə mütləqdir', 'ru' => 'Это поле обязательно', 'en' => 'This field is required'],
            ['key' => 'validation.email_invalid', 'group' => 'validation', 'az' => 'Yanlış email', 'ru' => 'Неверный email', 'en' => 'Invalid email'],
            ['key' => 'validation.password_min', 'group' => 'validation', 'az' => 'Şifrə ən az 8 simvol olmalıdır', 'ru' => 'Пароль должен содержать не менее 8 символов', 'en' => 'Password must be at least 8 characters'],
            ['key' => 'validation.password_mismatch', 'group' => 'validation', 'az' => 'Şifrələr uyğun gəlmir', 'ru' => 'Пароли не совпадают', 'en' => 'Passwords do not match'],
            ['key' => 'validation.username_format', 'group' => 'validation', 'az' => 'Yalnız hərflər, rəqəmlər və _ işarəsi', 'ru' => 'Только буквы, цифры и _', 'en' => 'Only letters, numbers and _'],
            ['key' => 'validation.min_length', 'group' => 'validation', 'az' => 'Ən az :min simvol', 'ru' => 'Минимум :min символов', 'en' => 'At least :min characters'],
            ['key' => 'validation.max_length', 'group' => 'validation', 'az' => 'Ən çox :max simvol', 'ru' => 'Максимум :max символов', 'en' => 'At most :max characters'],

            // ─── Achievement notifications ─────────────────────────────────────
            ['key' => 'achievement.earned', 'group' => 'achievements', 'az' => 'Nailiyyət qazandınız!', 'ru' => 'Достижение получено!', 'en' => 'Achievement earned!'],
            ['key' => 'achievement.xp_earned', 'group' => 'achievements', 'az' => '+:xp XP qazandınız', 'ru' => '+:xp XP получено', 'en' => '+:xp XP earned'],
            ['key' => 'achievements.earned_label', 'group' => 'achievements', 'az' => 'Qazanılmış', 'ru' => 'Получено', 'en' => 'Earned'],
            ['key' => 'achievements.locked_label', 'group' => 'achievements', 'az' => 'Kilidli', 'ru' => 'Заблокировано', 'en' => 'Locked'],
            ['key' => 'achievements.empty', 'group' => 'achievements', 'az' => 'Hələ nailiyyət yoxdur', 'ru' => 'Достижений пока нет', 'en' => 'No achievements yet. Start playing!'],
        ];

        foreach ($strings as $string) {
            SystemString::updateOrCreate(
                ['string_key' => $string['key']],
                [
                    'group_name' => $string['group'],
                    'az' => $string['az'],
                    'ru' => $string['ru'],
                    'en' => $string['en'],
                ]
            );
        }

        // ─── Localization audit additions ─────────────────────────────────
        $strings = array_merge($strings, [
            // Auth extras
            ['key' => 'auth.change_password', 'group' => 'auth', 'az' => 'Şifrəni dəyiş', 'ru' => 'Изменить пароль', 'en' => 'Change password'],
            ['key' => 'auth.check_email', 'group' => 'auth', 'az' => 'E-poçtunuzu yoxlayın', 'ru' => 'Проверьте почту', 'en' => 'Check your email'],
            ['key' => 'auth.child_username_hint', 'group' => 'auth', 'az' => 'Uşağın istifadəçi adını daxil edin', 'ru' => 'Введите имя пользователя ребёнка', 'en' => 'Enter child username'],
            ['key' => 'auth.child_username_placeholder', 'group' => 'auth', 'az' => 'uşaq_adi', 'ru' => 'имя_ребёнка', 'en' => 'child_username'],
            ['key' => 'auth.current_password', 'group' => 'auth', 'az' => 'Mövcud şifrə', 'ru' => 'Текущий пароль', 'en' => 'Current password'],
            ['key' => 'auth.language', 'group' => 'auth', 'az' => 'Dil', 'ru' => 'Язык', 'en' => 'Language'],
            ['key' => 'auth.login_subtitle', 'group' => 'auth', 'az' => 'Oxu marafonuna davam et', 'ru' => 'Продолжи марафон чтения', 'en' => 'Continue your reading marathon'],
            ['key' => 'auth.parent_username', 'group' => 'auth', 'az' => 'Valideyn istifadəçi adı', 'ru' => 'Имя пользователя родителя', 'en' => 'Parent username'],
            ['key' => 'auth.password_confirmation', 'group' => 'auth', 'az' => 'Şifrəni təsdiqlə', 'ru' => 'Подтвердите пароль', 'en' => 'Confirm password'],
            ['key' => 'auth.password_updated', 'group' => 'auth', 'az' => 'Şifrə yeniləndi', 'ru' => 'Пароль обновлён', 'en' => 'Password updated'],
            ['key' => 'auth.register_subtitle', 'group' => 'auth', 'az' => 'Oxu yolçuluğuna başla', 'ru' => 'Начни путь к чтению', 'en' => 'Start your reading journey'],
            ['key' => 'auth.reset_expiry', 'group' => 'auth', 'az' => 'Keçid müddəti bitib', 'ru' => 'Ссылка истекла', 'en' => 'Reset link expired'],
            ['key' => 'auth.reset_password_desc', 'group' => 'auth', 'az' => 'Yeni şifrənizi daxil edin', 'ru' => 'Введите новый пароль', 'en' => 'Enter your new password'],
            ['key' => 'auth.reset_sent', 'group' => 'auth', 'az' => 'Şifrə sıfırlama linki göndərildi', 'ru' => 'Ссылка для сброса отправлена', 'en' => 'Reset link sent'],

            // Achievements
            ['key' => 'achievements.earned', 'group' => 'achievements', 'az' => 'Qazanılıb', 'ru' => 'Получено', 'en' => 'Earned'],
            ['key' => 'achievements.locked', 'group' => 'achievements', 'az' => 'Kilidli', 'ru' => 'Заблокировано', 'en' => 'Locked'],
            ['key' => 'achievements.progress', 'group' => 'achievements', 'az' => 'İrəliləyiş', 'ru' => 'Прогресс', 'en' => 'Progress'],

            // Admin extras
            ['key' => 'admin.allowed_game_modes', 'group' => 'admin', 'az' => 'İcazəli oyun rejimləri', 'ru' => 'Разрешённые режимы игры', 'en' => 'Allowed game modes'],
            ['key' => 'admin.auth_settings', 'group' => 'admin', 'az' => 'Autentifikasiya parametrləri', 'ru' => 'Настройки аутентификации', 'en' => 'Auth settings'],
            ['key' => 'admin.default_locale', 'group' => 'admin', 'az' => 'Standart dil', 'ru' => 'Язык по умолчанию', 'en' => 'Default locale'],
            ['key' => 'admin.file_settings', 'group' => 'admin', 'az' => 'Fayl parametrləri', 'ru' => 'Настройки файлов', 'en' => 'File settings'],
            ['key' => 'admin.game_settings', 'group' => 'admin', 'az' => 'Oyun parametrləri', 'ru' => 'Настройки игры', 'en' => 'Game settings'],
            ['key' => 'admin.maintenance_mode', 'group' => 'admin', 'az' => 'Texniki baxım rejimi', 'ru' => 'Режим обслуживания', 'en' => 'Maintenance mode'],
            ['key' => 'admin.maintenance_mode_desc', 'group' => 'admin', 'az' => 'Platforma müvəqqəti bağlıdır', 'ru' => 'Платформа временно недоступна', 'en' => 'Platform is temporarily unavailable'],
            ['key' => 'admin.max_file_size', 'group' => 'admin', 'az' => 'Maksimum fayl ölçüsü (MB)', 'ru' => 'Максимальный размер файла (МБ)', 'en' => 'Max file size (MB)'],
            ['key' => 'admin.new_users_week', 'group' => 'admin', 'az' => 'Bu həftə yeni istifadəçilər', 'ru' => 'Новые пользователи за неделю', 'en' => 'New users this week'],
            ['key' => 'admin.no_competitions', 'group' => 'admin', 'az' => 'Müsabiqə yoxdur', 'ru' => 'Нет соревнований', 'en' => 'No competitions'],
            ['key' => 'admin.no_logs', 'group' => 'admin', 'az' => 'Jurnal yoxdur', 'ru' => 'Нет журналов', 'en' => 'No logs'],
            ['key' => 'admin.no_texts', 'group' => 'admin', 'az' => 'Mətn yoxdur', 'ru' => 'Нет текстов', 'en' => 'No texts'],
            ['key' => 'admin.platform', 'group' => 'admin', 'az' => 'Platforma', 'ru' => 'Платформа', 'en' => 'Platform'],
            ['key' => 'admin.quick_actions', 'group' => 'admin', 'az' => 'Sürətli əməliyyatlar', 'ru' => 'Быстрые действия', 'en' => 'Quick actions'],
            ['key' => 'admin.registration_open', 'group' => 'admin', 'az' => 'Qeydiyyat açıqdır', 'ru' => 'Регистрация открыта', 'en' => 'Registration open'],
            ['key' => 'admin.registration_open_desc', 'group' => 'admin', 'az' => 'Yeni istifadəçilər qeydiyyatdan keçə bilər', 'ru' => 'Новые пользователи могут регистрироваться', 'en' => 'New users can register'],
            ['key' => 'admin.select_role', 'group' => 'admin', 'az' => 'Rol seçin', 'ru' => 'Выберите роль', 'en' => 'Select role'],
            ['key' => 'admin.sessions_today', 'group' => 'admin', 'az' => 'Bu günün sessiyaları', 'ru' => 'Сессии за сегодня', 'en' => 'Sessions today'],
            ['key' => 'admin.sessions_week', 'group' => 'admin', 'az' => 'Bu həftənin sessiyaları', 'ru' => 'Сессии за неделю', 'en' => 'Sessions this week'],
            ['key' => 'admin.text_content_placeholder', 'group' => 'admin', 'az' => 'Mətn məzmununu daxil edin...', 'ru' => 'Введите содержимое текста...', 'en' => 'Enter text content...'],
            ['key' => 'admin.token_expiry', 'group' => 'admin', 'az' => 'Token müddəti (dəqiqə)', 'ru' => 'Срок токена (минуты)', 'en' => 'Token expiry (minutes)'],
            ['key' => 'admin.token_expiry_remember', 'group' => 'admin', 'az' => '"Məni xatırla" token müddəti', 'ru' => 'Срок токена "Запомнить меня"', 'en' => '"Remember me" token expiry'],
            ['key' => 'admin.total_students', 'group' => 'admin', 'az' => 'Ümumi tələbələr', 'ru' => 'Всего студентов', 'en' => 'Total students'],
            ['key' => 'admin.total_teachers', 'group' => 'admin', 'az' => 'Ümumi müəllimlər', 'ru' => 'Всего учителей', 'en' => 'Total teachers'],

            // Analytics extras
            ['key' => 'analytics.history_desc', 'group' => 'analytics', 'az' => 'Keçmiş sessiya nəticələriniz', 'ru' => 'Ваши предыдущие результаты', 'en' => 'Your past session results'],
            ['key' => 'analytics.no_sessions', 'group' => 'analytics', 'az' => 'Hələ sessiya yoxdur', 'ru' => 'Сессий пока нет', 'en' => 'No sessions yet'],
            ['key' => 'analytics.recent_sessions', 'group' => 'analytics', 'az' => 'Son sessiyalar', 'ru' => 'Последние сессии', 'en' => 'Recent sessions'],

            // Common extras
            ['key' => 'common.age_group', 'group' => 'common', 'az' => 'Yaş qrupu', 'ru' => 'Возрастная группа', 'en' => 'Age group'],
            ['key' => 'common.all_time', 'group' => 'common', 'az' => 'Bütün vaxt', 'ru' => 'За всё время', 'en' => 'All time'],
            ['key' => 'common.clear', 'group' => 'common', 'az' => 'Təmizlə', 'ru' => 'Очистить', 'en' => 'Clear'],
            ['key' => 'common.content', 'group' => 'common', 'az' => 'Məzmun', 'ru' => 'Содержимое', 'en' => 'Content'],
            ['key' => 'common.date_from', 'group' => 'common', 'az' => 'Tarixdən', 'ru' => 'С даты', 'en' => 'Date from'],
            ['key' => 'common.date_to', 'group' => 'common', 'az' => 'Tarixə qədər', 'ru' => 'По дату', 'en' => 'Date to'],
            ['key' => 'common.deleted', 'group' => 'common', 'az' => 'Silindi', 'ru' => 'Удалено', 'en' => 'Deleted'],
            ['key' => 'common.difficulty', 'group' => 'common', 'az' => 'Çətinlik', 'ru' => 'Сложность', 'en' => 'Difficulty'],
            ['key' => 'common.ends_at', 'group' => 'common', 'az' => 'Bitmə tarixi', 'ru' => 'Дата окончания', 'en' => 'Ends at'],
            ['key' => 'common.group', 'group' => 'common', 'az' => 'Qrup', 'ru' => 'Группа', 'en' => 'Group'],
            ['key' => 'common.key', 'group' => 'common', 'az' => 'Açar', 'ru' => 'Ключ', 'en' => 'Key'],
            ['key' => 'common.next', 'group' => 'common', 'az' => 'Növbəti', 'ru' => 'Далее', 'en' => 'Next'],
            ['key' => 'common.not_now', 'group' => 'common', 'az' => 'İndi yox', 'ru' => 'Не сейчас', 'en' => 'Not now'],
            ['key' => 'common.permissions_for', 'group' => 'common', 'az' => 'İcazələr:', 'ru' => 'Разрешения:', 'en' => 'Permissions for:'],
            ['key' => 'common.prev', 'group' => 'common', 'az' => 'Əvvəlki', 'ru' => 'Назад', 'en' => 'Previous'],
            ['key' => 'common.roles', 'group' => 'common', 'az' => 'Rollar', 'ru' => 'Роли', 'en' => 'Roles'],
            ['key' => 'common.saved', 'group' => 'common', 'az' => 'Yadda saxlandı', 'ru' => 'Сохранено', 'en' => 'Saved'],
            ['key' => 'common.starts_at', 'group' => 'common', 'az' => 'Başlama tarixi', 'ru' => 'Дата начала', 'en' => 'Starts at'],
            ['key' => 'common.system', 'group' => 'common', 'az' => 'Sistem', 'ru' => 'Система', 'en' => 'System'],
            ['key' => 'common.title', 'group' => 'common', 'az' => 'Başlıq', 'ru' => 'Заголовок', 'en' => 'Title'],
            ['key' => 'common.toggle_active', 'group' => 'common', 'az' => 'Aktiv/Deaktiv et', 'ru' => 'Активировать/Деактивировать', 'en' => 'Toggle active'],
            ['key' => 'common.total', 'group' => 'common', 'az' => 'Cəmi', 'ru' => 'Итого', 'en' => 'Total'],
            ['key' => 'common.unlimited', 'group' => 'common', 'az' => 'Limitsiz', 'ru' => 'Без ограничений', 'en' => 'Unlimited'],
            ['key' => 'common.updated', 'group' => 'common', 'az' => 'Yeniləndi', 'ru' => 'Обновлено', 'en' => 'Updated'],
            ['key' => 'common.uploaded', 'group' => 'common', 'az' => 'Yükləndi', 'ru' => 'Загружено', 'en' => 'Uploaded'],
            ['key' => 'common.username', 'group' => 'common', 'az' => 'İstifadəçi adı', 'ru' => 'Имя пользователя', 'en' => 'Username'],
            ['key' => 'common.view_all', 'group' => 'common', 'az' => 'Hamısını gör', 'ru' => 'Посмотреть все', 'en' => 'View all'],
            ['key' => 'common.you', 'group' => 'common', 'az' => 'Siz', 'ru' => 'Вы', 'en' => 'You'],

            // Dashboard
            ['key' => 'dashboard.welcome', 'group' => 'dashboard', 'az' => 'Xoş gəldiniz', 'ru' => 'Добро пожаловать', 'en' => 'Welcome'],
            ['key' => 'dashboard.student_subtitle', 'group' => 'dashboard', 'az' => 'Bugün hansı rekord qıracaqsan?', 'ru' => 'Какой рекорд побьёшь сегодня?', 'en' => 'What record will you break today?'],
            ['key' => 'dashboard.teacher_subtitle', 'group' => 'dashboard', 'az' => 'Tələbələrinizin irəliləyişi', 'ru' => 'Прогресс ваших студентов', 'en' => 'Your students\' progress'],
            ['key' => 'dashboard.admin_subtitle', 'group' => 'dashboard', 'az' => 'Platformaya ümumi baxış', 'ru' => 'Обзор платформы', 'en' => 'Platform overview'],
            ['key' => 'dashboard.parent_subtitle', 'group' => 'dashboard', 'az' => 'Uşaqlarınızın irəliləyişi', 'ru' => 'Прогресс ваших детей', 'en' => 'Your children\'s progress'],

            // Errors
            ['key' => 'errors.generic', 'group' => 'errors', 'az' => 'Xəta baş verdi', 'ru' => 'Произошла ошибка', 'en' => 'Something went wrong'],
            ['key' => 'errors.invalid_password', 'group' => 'errors', 'az' => 'Şifrə yanlışdır', 'ru' => 'Неверный пароль', 'en' => 'Invalid password'],

            // Game extras
            ['key' => 'game.auto_select', 'group' => 'game', 'az' => 'Avtomatik seçim', 'ru' => 'Авто-выбор', 'en' => 'Auto select'],
            ['key' => 'game.completed', 'group' => 'game', 'az' => 'Tamamlandı', 'ru' => 'Завершено', 'en' => 'Completed'],
            ['key' => 'game.completion', 'group' => 'game', 'az' => 'Tamamlama', 'ru' => 'Завершение', 'en' => 'Completion'],
            ['key' => 'game.mode_memory', 'group' => 'game', 'az' => 'Yaddaş', 'ru' => 'Память', 'en' => 'Memory'],
            ['key' => 'game.mode_random', 'group' => 'game', 'az' => 'Təsadüfi sözlər', 'ru' => 'Случайные слова', 'en' => 'Random words'],
            ['key' => 'game.mode_sentence', 'group' => 'game', 'az' => 'Cümlə oxuma', 'ru' => 'Чтение предложений', 'en' => 'Sentence reading'],
            ['key' => 'game.mode_text', 'group' => 'game', 'az' => 'Mətn oxuma', 'ru' => 'Чтение текста', 'en' => 'Text reading'],
            ['key' => 'game.no_permission', 'group' => 'game', 'az' => 'Oyun oynamaq icazəniz yoxdur', 'ru' => 'У вас нет разрешения играть', 'en' => 'You don\'t have permission to play'],
            ['key' => 'game.paused', 'group' => 'game', 'az' => 'Fasilə', 'ru' => 'Пауза', 'en' => 'Paused'],
            ['key' => 'game.resume', 'group' => 'game', 'az' => 'Davam et', 'ru' => 'Продолжить', 'en' => 'Resume'],
            ['key' => 'game.seconds', 'group' => 'game', 'az' => 'saniyə', 'ru' => 'сек', 'en' => 'seconds'],
            ['key' => 'game.word_list', 'group' => 'game', 'az' => 'Söz siyahısı', 'ru' => 'Список слов', 'en' => 'Word list'],
            ['key' => 'game.words', 'group' => 'game', 'az' => 'Sözlər', 'ru' => 'Слова', 'en' => 'Words'],

            // Gamification extras
            ['key' => 'gamification.stats', 'group' => 'gamification', 'az' => 'Statistika', 'ru' => 'Статистика', 'en' => 'Stats'],
            ['key' => 'gamification.streak_days', 'group' => 'gamification', 'az' => 'günlük seriya', 'ru' => 'дней подряд', 'en' => 'day streak'],

            // Nav extras
            ['key' => 'nav.classes', 'group' => 'nav', 'az' => 'Siniflər', 'ru' => 'Классы', 'en' => 'Classes'],
            ['key' => 'nav.notifications', 'group' => 'nav', 'az' => 'Bildirişlər', 'ru' => 'Уведомления', 'en' => 'Notifications'],
            ['key' => 'nav.progress', 'group' => 'nav', 'az' => 'İrəliləyiş', 'ru' => 'Прогресс', 'en' => 'Progress'],

            // Notifications / Push
            ['key' => 'notifications.mark_read', 'group' => 'notifications', 'az' => 'Oxunmuş kimi işarələ', 'ru' => 'Отметить прочитанным', 'en' => 'Mark as read'],
            ['key' => 'notifications.push_blocked', 'group' => 'notifications', 'az' => 'Bildirişlər brauzer parametrlərindən bloklanıb', 'ru' => 'Уведомления заблокированы в браузере', 'en' => 'Notifications blocked in browser settings'],
            ['key' => 'notifications.push_denied', 'group' => 'notifications', 'az' => 'Bildirişlərə icazə verilmədi', 'ru' => 'Уведомления отклонены', 'en' => 'Notifications blocked. Enable in browser settings.'],
            ['key' => 'notifications.push_disable', 'group' => 'notifications', 'az' => 'Bildirişləri söndür', 'ru' => 'Отключить уведомления', 'en' => 'Disable notifications'],
            ['key' => 'notifications.push_enable', 'group' => 'notifications', 'az' => 'Bildirişləri aktivləşdir', 'ru' => 'Включить уведомления', 'en' => 'Enable notifications'],
            ['key' => 'notifications.push_enabled', 'group' => 'notifications', 'az' => 'Push bildirişlər aktivdir!', 'ru' => 'Push-уведомления включены!', 'en' => 'Push notifications enabled!'],
            ['key' => 'notifications.push_prompt_body', 'group' => 'notifications', 'az' => 'Nailiyyətlər, səviyyə artımları və seriyalar haqqında bildiriş alın.', 'ru' => 'Получайте уведомления о достижениях, повышениях уровня и сериях.', 'en' => 'Get notified about achievements, level-ups, and streaks.'],
            ['key' => 'notifications.push_prompt_title', 'group' => 'notifications', 'az' => 'İrəliləyişinizdən xəbərdar olun!', 'ru' => 'Следите за своим прогрессом!', 'en' => 'Stay on top of your progress!'],
            ['key' => 'notifications.push_unsupported', 'group' => 'notifications', 'az' => 'Bu brauzer push bildirişlərini dəstəkləmir', 'ru' => 'Этот браузер не поддерживает push-уведомления', 'en' => 'Push notifications not supported in this browser'],

            // Parent extras
            ['key' => 'parent.link_child_hint', 'group' => 'parent', 'az' => 'Uşağı qoşmaq üçün onun istifadəçi adını daxil edin', 'ru' => 'Введите имя пользователя ребёнка для привязки', 'en' => 'Enter child username to link them to your account'],

            // Profile extras
            ['key' => 'profile.desc', 'group' => 'profile', 'az' => 'Profil məlumatlarınızı idarə edin', 'ru' => 'Управляйте данными профиля', 'en' => 'Manage your profile information'],
            ['key' => 'profile.first_name', 'group' => 'profile', 'az' => 'Ad', 'ru' => 'Имя', 'en' => 'First name'],
            ['key' => 'profile.last_name', 'group' => 'profile', 'az' => 'Soyad', 'ru' => 'Фамилия', 'en' => 'Last name'],

            // School / Class
            ['key' => 'school.name', 'group' => 'schools', 'az' => 'Məktəb adı', 'ru' => 'Название школы', 'en' => 'School name'],
            ['key' => 'school.select', 'group' => 'schools', 'az' => 'Məktəb seçin', 'ru' => 'Выберите школу', 'en' => 'Select school'],
            ['key' => 'class.name', 'group' => 'common', 'az' => 'Sinif adı', 'ru' => 'Название класса', 'en' => 'Class name'],
            ['key' => 'class.select', 'group' => 'common', 'az' => 'Sinif seçin', 'ru' => 'Выберите класс', 'en' => 'Select class'],

            // Settings
            ['key' => 'settings.language', 'group' => 'settings', 'az' => 'Dil', 'ru' => 'Язык', 'en' => 'Language'],

            // Teacher extras
            ['key' => 'teacher.sessions_today', 'group' => 'teacher', 'az' => 'Bu günün sessiyaları', 'ru' => 'Сессии за сегодня', 'en' => 'Sessions today'],
            ['key' => 'teacher.sessions_week', 'group' => 'teacher', 'az' => 'Bu həftənin sessiyaları', 'ru' => 'Сессии за неделю', 'en' => 'Sessions this week'],
            ['key' => 'teacher.view_progress', 'group' => 'teacher', 'az' => 'İrəliləyişi gör', 'ru' => 'Посмотреть прогресс', 'en' => 'View progress'],

            // Words extras
            ['key' => 'words.export_csv', 'group' => 'words', 'az' => 'CSV ixrac et', 'ru' => 'Экспортировать CSV', 'en' => 'Export CSV'],
            ['key' => 'words.import_csv', 'group' => 'words', 'az' => 'CSV idxal et', 'ru' => 'Импортировать CSV', 'en' => 'Import CSV'],
            ['key' => 'words.import_success', 'group' => 'words', 'az' => '{imported} söz idxal edildi, {skipped} atlandı', 'ru' => '{imported} слов импортировано, {skipped} пропущено', 'en' => '{imported} words imported, {skipped} skipped'],

            // Broadcast / admin notifications
            ['key' => 'notifications.broadcast_sent', 'group' => 'notifications', 'az' => 'Yayım bildirişi göndərildi', 'ru' => 'Широковещательное уведомление отправлено', 'en' => 'Broadcast notification sent'],
            ['key' => 'notifications.new_broadcast', 'group' => 'notifications', 'az' => 'Yayım göndər', 'ru' => 'Отправить рассылку', 'en' => 'Send Broadcast'],
            ['key' => 'notifications.message', 'group' => 'notifications', 'az' => 'Mesaj', 'ru' => 'Сообщение', 'en' => 'Message'],
            ['key' => 'notifications.audience', 'group' => 'notifications', 'az' => 'Tamaşaçılar', 'ru' => 'Аудитория', 'en' => 'Audience'],
            ['key' => 'notifications.broadcast_title_placeholder', 'group' => 'notifications', 'az' => 'məs. Yeni söz siyahıları əlavə edildi!', 'ru' => 'напр. Добавлены новые списки слов!', 'en' => 'e.g. New word lists added!'],
            ['key' => 'notifications.broadcast_message_placeholder', 'group' => 'notifications', 'az' => 'Mesajınızı buraya yazın...', 'ru' => 'Напишите ваше сообщение здесь...', 'en' => 'Write your message here...'],
            ['key' => 'notifications.target_all', 'group' => 'notifications', 'az' => 'Bütün istifadəçilər', 'ru' => 'Все пользователи', 'en' => 'All users'],
            ['key' => 'notifications.target_students', 'group' => 'notifications', 'az' => 'Yalnız tələbələr', 'ru' => 'Только студенты', 'en' => 'Students only'],
            ['key' => 'notifications.target_teachers', 'group' => 'notifications', 'az' => 'Yalnız müəllimlər', 'ru' => 'Только учителя', 'en' => 'Teachers only'],
            ['key' => 'notifications.target_parents', 'group' => 'notifications', 'az' => 'Yalnız valideynlər', 'ru' => 'Только родители', 'en' => 'Parents only'],
            ['key' => 'notifications.send_broadcast', 'group' => 'notifications', 'az' => 'Bildiriş göndər', 'ru' => 'Отправить уведомление', 'en' => 'Send notification'],
            ['key' => 'notifications.broadcast_delivered', 'group' => 'notifications', 'az' => 'Yayım çatdırıldı!', 'ru' => 'Рассылка доставлена!', 'en' => 'Broadcast delivered!'],
            ['key' => 'notifications.recipients', 'group' => 'notifications', 'az' => 'alıcı', 'ru' => 'получателей', 'en' => 'recipients'],
            ['key' => 'notifications.broadcast_tips_title', 'group' => 'notifications', 'az' => 'İpuçları', 'ru' => 'Советы', 'en' => 'Tips'],
            ['key' => 'notifications.tip_1', 'group' => 'notifications', 'az' => 'Yayımlar tətbaxarxası verilənlər bazası bildirişləri və abunə olunmuş cihazlara push bildirişlər kimi göndərilir.', 'ru' => 'Рассылки отправляются как внутренние уведомления и push-уведомления на подписанные устройства.', 'en' => 'Broadcasts are sent as in-app database notifications and push notifications to subscribed devices.'],
            ['key' => 'notifications.tip_2', 'group' => 'notifications', 'az' => 'Başlığı qısa saxlayın — push bildirişi üçün ideal olaraq 60 simvoldan az.', 'ru' => 'Держите заголовок коротким — идеально менее 60 символов для push-уведомлений.', 'en' => 'Keep titles short — under 60 characters is ideal for push notification display.'],
            ['key' => 'notifications.tip_3', 'group' => 'notifications', 'az' => 'Bildiriş yorğunluğunun qarşısını almaq üçün hədəf seqmentasiyasından istifadə edin.', 'ru' => 'Используйте таргетинг для снижения усталости от уведомлений.', 'en' => 'Use audience targeting to avoid notification fatigue.'],
            ['key' => 'admin.notifications_desc', 'group' => 'admin', 'az' => 'Rol əsasında istifadəçilərə kütləvi bildirişlər göndərin.', 'ru' => 'Отправляйте массовые уведомления пользователям по ролям.', 'en' => 'Send broadcast notifications to users by role.'],

            // Common sending state
            ['key' => 'common.sending', 'group' => 'common', 'az' => 'Göndərilir...', 'ru' => 'Отправка...', 'en' => 'Sending...'],

            // Parent progress page
            ['key' => 'parent.progress_desc', 'group' => 'parent', 'az' => 'Uşaqlarınızın oxu performansını müqayisəli izləyin.', 'ru' => 'Отслеживайте успехи детей в чтении рядом.', 'en' => 'Track your children\'s reading performance side by side.'],
            ['key' => 'parent.no_children', 'group' => 'parent', 'az' => 'Hesabınıza bağlı uşaq yoxdur.', 'ru' => 'К вашему аккаунту не привязаны дети.', 'en' => 'No children linked to your account.'],
            ['key' => 'parent.add_child', 'group' => 'parent', 'az' => 'Uşaq əlavə et', 'ru' => 'Добавить ребёнка', 'en' => 'Add a child'],
            ['key' => 'parent.view_detail', 'group' => 'parent', 'az' => 'Ətraflı məlumat', 'ru' => 'Подробнее', 'en' => 'Full detail'],

            // Teacher classes page
            ['key' => 'teacher.classes_desc', 'group' => 'teacher', 'az' => 'Siniflərinizdəki tələbələri idarə edin.', 'ru' => 'Управляйте учениками в ваших классах.', 'en' => 'Manage students in your classes.'],
            ['key' => 'teacher.no_classes', 'group' => 'teacher', 'az' => 'Sizin sinifiniz yoxdur.', 'ru' => 'У вас нет классов.', 'en' => 'You have no classes assigned.'],
            ['key' => 'teacher.grade', 'group' => 'teacher', 'az' => 'Sinif', 'ru' => 'Класс', 'en' => 'Grade'],
            ['key' => 'teacher.no_students', 'group' => 'teacher', 'az' => 'Bu sinifdə tələbə yoxdur.', 'ru' => 'В этом классе нет учеников.', 'en' => 'No students in this class.'],

            // AI game mode
            ['key' => 'game.ai_mode', 'group' => 'game', 'az' => 'Süni İntelekt', 'ru' => 'ИИ-режим', 'en' => 'AI Mode'],
            ['key' => 'game.ai_desc', 'group' => 'game', 'az' => 'Şəxsiləşdirilmiş — zəif sözlərinizə əsaslanan adaptiv məşq.', 'ru' => 'Персонализированная адаптивная тренировка на основе слабых слов.', 'en' => 'Personalised — adaptive training based on your weakest words.'],
            ['key' => 'game.ai_profile_title', 'group' => 'game', 'az' => 'Süni İntelekt Məşq Profiliniz', 'ru' => 'Ваш профиль ИИ-тренировки', 'en' => 'Your AI Training Profile'],
            ['key' => 'game.ai_weak_words', 'group' => 'game', 'az' => 'zəif söz izlənilir', 'ru' => 'слабых слов отслежено', 'en' => 'weak words tracked'],
            ['key' => 'game.ai_sessions', 'group' => 'game', 'az' => '{n} sessiya analiz edildi', 'ru' => '{n} сессий проанализировано', 'en' => '{n} sessions analyzed'],
            ['key' => 'game.ai_not_enough_data', 'group' => 'game', 'az' => 'Tam şəxsiləşdirməni açmaq üçün bir neçə sessiya daha oynayın. Boşluqları təsadüfi sözlər dolduracaq.', 'ru' => 'Сыграйте ещё несколько сессий для полной персонализации. Пробелы заполнят случайные слова.', 'en' => 'Play a few more sessions to unlock full personalization. Random words will fill the gaps.'],
            ['key' => 'game.ai_focus_words', 'group' => 'game', 'az' => 'Fokus sözlər:', 'ru' => 'Слова для работы:', 'en' => 'Focus words:'],
            ['key' => 'game.ai_no_history', 'group' => 'game', 'az' => 'Hələ tarix yoxdur. Süni İntelekt ümumi söz dəstlərindən başlayacaq və oynandıqca uyğunlaşacaq.', 'ru' => 'Истории пока нет. ИИ начнёт с общих наборов слов и адаптируется по мере игры.', 'en' => 'No session history yet. AI will start with general word sets and adapt as you play.'],
            ['key' => 'game.ai_targeted', 'group' => 'game', 'az' => 'hədəflənib', 'ru' => 'целевых', 'en' => 'targeted'],
            ['key' => 'game.ai_insights_title', 'group' => 'game', 'az' => 'Süni İntelekt Məşq Nəticələri', 'ru' => 'Аналитика ИИ-тренировки', 'en' => 'AI Training Insights'],
            ['key' => 'game.ai_targeted_read', 'group' => 'game', 'az' => 'Fokus söz oxundu', 'ru' => 'Прочитано целевых слов', 'en' => 'Focus words read'],
            ['key' => 'game.ai_targeted_rate', 'group' => 'game', 'az' => 'Fokus söz dərəcəsi', 'ru' => 'Доля целевых слов', 'en' => 'Focus word rate'],
            ['key' => 'game.ai_great_focus', 'group' => 'game', 'az' => 'Fokus sözlərinizdə əla iş! Növbəti sessiyada çətinlik artacaq.', 'ru' => 'Отличная работа с целевыми словами! В следующей сессии сложность возрастёт.', 'en' => 'Great job on your focus words! Difficulty will increase next session.'],
            ['key' => 'game.ai_keep_going', 'group' => 'game', 'az' => 'Fokus sözlərinizdə yaxşı irəliləyiş. Onları mənimsəmək üçün məşq etməyə davam edin.', 'ru' => 'Хороший прогресс с целевыми словами. Продолжайте тренироваться.', 'en' => 'Good progress on focus words. Keep practicing to master them.'],
            ['key' => 'game.ai_needs_work', 'group' => 'game', 'az' => 'Bu sözlər daha çox məşq tələb edir. Süni İntelekt onları növbəti sessiyada prioritetləşdirəcək.', 'ru' => 'Эти слова требуют большей практики. ИИ приоритизирует их в следующей сессии.', 'en' => 'These words need more practice. AI will prioritize them next session.'],
        ]);

        $this->command->info('System strings seeded: ' . count($strings) . ' entries.');
    }
}
